### ISSUE TITLE
[1.20.1-Forge] Mixin apply for mod failed mixins.json:GrassBlockMixin

### ISSUE THREAD

**Issue by PhweeDev** [Potion-Studios/Oh-The-Biomes-Weve-Gone#1]
When loading a pack with mods [Missing Wilds](https://github.com/UltrusBot/missing-wilds/tree/1.20) and [Environmental](https://github.com/team-abnormals/environmental/tree/1.20.x), the game crashes on start-up, Both crashes are similar in their cause, their log links are below.

https://paste.gg/p/anonymous/a50c9c52b5ab42b2894351d2bcfb02b8
and
https://paste.gg/p/anonymous/997702b1ab054de2b3ea177dfad94ffa

They're both easy to replicate

-Have BWG and all the dependencies
-Download Missing Wilds Forge (fastest route, same bug with environmental and missing wilds forge is faster to just grab)
-Try and load the game on the latest 1.20.1 Forge version
-Crash

**Comment by RoomAlex68** [comment]
I'm having the same error as well when having with just oh the biomes we've gone and all the mods dependencies

**Comment by JT122406** [comment]
> When loading a pack with mods [Missing Wilds](https://github.com/UltrusBot/missing-wilds/tree/1.20) and [Environmental](https://github.com/team-abnormals/environmental/tree/1.20.x), the game crashes on start-up, Both crashes are similar in their cause, their log links are below.
> 
> https://paste.gg/p/anonymous/a50c9c52b5ab42b2894351d2bcfb02b8 and https://paste.gg/p/anonymous/997702b1ab054de2b3ea177dfad94ffa
> 
> They're both easy to replicate
> 
> -Have BWG and all the dependencies -Download Missing Wilds Forge (fastest route, same bug with environmental and missing wilds forge is faster to just grab) -Try and load the game on the latest 1.20.1 Forge version -Crash

The reason for this is because we both mixin to GrassBlock.java causing a conflict so unless I can find another way to do this without a mixin or they can then we are stuck being incompatible

**Comment by JT122406** [comment]
> I'm having the same error as well on Forge when I just have oh the biomes we've gone and it's mod dependencies

This however I need a log for as this shouldn't be happening

**Comment by PhweeDev** [comment]
> > When loading a pack with mods [Missing Wilds](https://github.com/UltrusBot/missing-wilds/tree/1.20) and [Environmental](https://github.com/team-abnormals/environmental/tree/1.20.x), the game crashes on start-up, Both crashes are similar in their cause, their log links are below.
> > https://paste.gg/p/anonymous/a50c9c52b5ab42b2894351d2bcfb02b8 and https://paste.gg/p/anonymous/997702b1ab054de2b3ea177dfad94ffa
> > They're both easy to replicate
> > -Have BWG and all the dependencies -Download Missing Wilds Forge (fastest route, same bug with environmental and missing wilds forge is faster to just grab) -Try and load the game on the latest 1.20.1 Forge version -Crash
> 
> The reason for this is because we both mixin to GrassBlock.java causing a conflict so unless I can find another way to do this without a mixin or they can then we are stuck being incompatible

Gotcha, I'll leave this issue open for now. Feel free to close it if you cannot find any workaround for it!

**Comment by RoomAlex68** [comment]
> > I'm having the same error as well on Forge when I just have oh the biomes we've gone and it's mod dependencies
> 
> This however I need a log for as this shouldn't be happening


Here is my crash log
![crash-2024-07-28_12.06.09-client.txt](https://github.com/user-attachments/files/16404934/crash-2024-07-28_12.06.09-client.txt)

**Comment by JT122406** [comment]
> > > I'm having the same error as well on Forge when I just have oh the biomes we've gone and it's mod dependencies
> > 
> > 
> > This however I need a log for as this shouldn't be happening
> 
> [ezyzip.zip](https://github.com/user-attachments/files/16404948/ezyzip.zip)

dlopen failed: library "libflite.so" not found
Not us

**Comment by RoomAlex68** [comment]
> > > > I'm having the same error as well on Forge when I just have oh the biomes we've gone and it's mod dependencies
> > > 
> > > 
> > > This however I need a log for as this shouldn't be happening
> > 
> > [ezyzip.zip](https://github.com/user-attachments/files/16404948/ezyzip.zip)
> 
> dlopen failed: library "libflite.so" not found
> Not us

Here's the crash log as well:
![crash-2024-07-28_12.06.09-client.txt](https://github.com/user-attachments/files/16405311/crash-2024-07-28_12.06.09-client.txt)

**Comment by JT122406** [comment]
> > > > > I'm having the same error as well on Forge when I just have oh the biomes we've gone and it's mod dependencies
> > > > 
> > > > 
> > > > This however I need a log for as this shouldn't be happening
> > > 
> > > 
> > > [ezyzip.zip](https://github.com/user-attachments/files/16404948/ezyzip.zip)
> > 
> > 
> > dlopen failed: library "libflite.so" not found
> > Not us
> 
> Here's the crash log as well: ![crash-2024-07-28_12.06.09-client.txt](https://github.com/user-attachments/files/16405311/crash-2024-07-28_12.06.09-client.txt)

CorgiLib Crash

**Comment by JT122406** [comment]
I have just fixed this on the Forge Side, I have not found a way to deal with it on the fabric side but it'll fix the incompatibility on the Forge side
