### ISSUE TITLE
Incompatibility between alex's mobs and biomes weve gone

### ISSUE THREAD

**Issue by 77Delta** [Potion-Studios/Oh-The-Biomes-Weve-Gone#103]
I don't know if im having bad luck or something but alex's mobs dont spawn in any of the bwg biomes.

Just in case here's a list of the mods i have: https://pastebin.com/V54i4GKa (Forge version: 1.20.1 47.3.0)

**Comment by JT122406** [comment]
This would be an issue with alex's mobs and not with bwg we add most of our biomes to vanilla and loader tags so it's up to them to use them.  Our tags were improved in 1.1.0-Beta so verify you are using that or newer as that might help
