### ISSUE TITLE
Fabric 1.20.1 No biomes spawning

### ISSUE THREAD

**Issue by Gamerbolts** [Potion-Studios/Oh-The-Biomes-Weve-Gone#104]
Hello!

I am creating a custom modpack and added this mod in for the new biomes. I spawned into the world however and tried the locate command and found no biomes anywhere. I am not sure why that would be I am using BetterX mods which when creating the world uses the BetterX generation instead of Default could that be why? Below are my log and my config file. Any help is appreciated.

[world_generation.txt](https://github.com/user-attachments/files/16785082/world_generation.txt)
https://www.dropbox.com/scl/fi/pjxru7b1lpvph5asj2a4j/latest.log?rlkey=zyaytxlz35gotpydvfml84okl&st=1bbad2o2&dl=0
Apologies for the dropbox link for the log, Github would not let me upload it.

Fabric 1.20.1 (0.15.11)
Biomes Weve Gone v1.1.1-Beta

**Comment by JT122406** [comment]
This is a new world?

**Comment by JT122406** [comment]
Also it shouldn't make a difference but use 1.1.2-Beta and fabric loader >= 0.16

**Comment by Gamerbolts** [comment]
Yep this is a brand new world. I did try 1.1.2-beta and fabric 0.16.3 as well and it was the same issue

**Comment by JT122406** [comment]
> Yep this is a brand new world. I did try 1.1.2-beta and fabric 0.16.3 as well and it was the same issue

Can you list all the mods that affect world gen

**Comment by Gamerbolts** [comment]
ok here are the list of world gen affected mods in alphabetical order:

Abridged
Ad Astra
Additional Structures
AdventureZ
AE2
Archon
Assorted World
Awesome Dungeon (Nether, Ocean and End additions)
Beneath The Wetlands
BetterEnd
BetterNether
Bewitchment
Bosses of Mass Destruction
Botania (Flowers)
ChoiceTheorem's Overhauled Village
Cobblemon
Deeper and Darker
Dungeon Now Loading 1%
Dungeons and Taverns
DungeonZ
Eldritch End
Explorify
Fabric Seasons (Not worldgen but does effect biomes I believe)
Farmer's Structures
Gigeresque
IceandFire Fabric
Macaw's Bridges
Mine Cells
MVS Moog's Voyager Structures
Nature Arise
Paradise Lost
Pumped Desert 2
Repurposed Structures
Simply Houses
Spectrum
The Bumblezone
The Graveyard
The Starlands Dimension
Tidal Towns
Towers of the Wild
Ultris Boss Expansion
Underground Villages
YUNG's Mods (Desert Temples, Dungeons, End Island, Jungle Temples, Mineshafts, Nether Fortresses, Ocean Monuments, Strongholds, Witch Huts, Bridges)

That should cover it for the world gen type mods. I have tried deleting all the config files and doing a new world a few times and still the same issue. It can't find any biome I tried structure as well and cannot find it.

**Comment by Gamerbolts** [comment]
I just downloaded the world preview mod which shows which biomes should be spawning. It does show bwg biomes I found the coords and went and it was a Minecraft Plains biome. not a bwg biome. It's gotta be a conflict but I am not sure what one.

**Comment by JT122406** [comment]
I wonder if it's a terrablender issue, do you have bop or another mod that uses terra that is working?

**Comment by Gamerbolts** [comment]
It possibly could be, I have Nature Arise. And I tried searching for those biomes and came up empty as well. Also have Generations Structures/Core that rely on Terrablender

**Comment by JT122406** [comment]
I make gens and they don’t rely on terrablender but do you think you could try installing like bop in a test world with ours see if anything gens

**Comment by Gamerbolts** [comment]
Sure I can try that. Oh I was thinking it did. I deactivated terrablender on CF and it deactivated that one lol

**Comment by JT122406** [comment]
That's weird

**Comment by JT122406** [comment]
I'll have to check that out

**Comment by Gamerbolts** [comment]
ok test world with bwg and all dependencies worked I was able to locate biomes. So it is something else in my pack

**Comment by Gamerbolts** [comment]
Also I completely forgot, was having issues with generations so I had manually deactivated that waiting for a fix :) sorry about that lol

**Comment by Gamerbolts** [comment]
After testing and testing my mods I found out The Starlands Dimension is to blame. https://www.curseforge.com/minecraft/mc-mods/the-starlands-dimension I am not sure whose end it is on but just thought you should know. I'll go ahead and post there as well.

**Comment by JT122406** [comment]
> After testing and testing my mods I found out The Starlands Dimension is to blame. https://www.curseforge.com/minecraft/mc-mods/the-starlands-dimension I am not sure whose end it is on but just thought you should know. I'll go ahead and post there as well.

Do you know if they do anything to the overworld?

**Comment by Gamerbolts** [comment]
> > After testing and testing my mods I found out The Starlands Dimension is to blame. https://www.curseforge.com/minecraft/mc-mods/the-starlands-dimension I am not sure whose end it is on but just thought you should know. I'll go ahead and post there as well.
> 
> Do you know if they do anything to the overworld?

When I installed the mod I thought it was a dimension because of the name of the mod however when spawning into the world I saw biomes from that mod

**Comment by JT122406** [comment]
> > > After testing and testing my mods I found out The Starlands Dimension is to blame. https://www.curseforge.com/minecraft/mc-mods/the-starlands-dimension I am not sure whose end it is on but just thought you should know. I'll go ahead and post there as well.
> > 
> > 
> > Do you know if they do anything to the overworld?
> 
> When I installed the mod I thought it was a dimension because of the name of the mod however when spawning into the world I saw biomes from that mod

Does the mod require terrablender?

**Comment by Gamerbolts** [comment]
> > > > After testing and testing my mods I found out The Starlands Dimension is to blame. https://www.curseforge.com/minecraft/mc-mods/the-starlands-dimension I am not sure whose end it is on but just thought you should know. I'll go ahead and post there as well.
> > > 
> > > 
> > > Do you know if they do anything to the overworld?
> > 
> > 
> > When I installed the mod I thought it was a dimension because of the name of the mod however when spawning into the world I saw biomes from that mod
> 
> Does the mod require terrablender?

Nope no dependencies

**Comment by JT122406** [comment]
That might be why, I assume it’s overriding what terrablender is trying to do to add our biomes to the world

**Comment by Gamerbolts** [comment]
> That might be why, I assume it’s overriding what terrablender is trying to do to add our biomes to the world

Yeah that may be it. After looking more into that mod didn't look like something I wanted so removed it from my pack. Didn't look like a well coded mod if it was breaking biomes like that.

**Comment by JT122406** [comment]
Welp I'm gonna close this and just chalk it up to them not using terrablender and stuff
