### ISSUE TITLE
world crash on singleplayer world

### ISSUE THREAD

**Issue by espressokofie** [Potion-Studios/Oh-The-Biomes-Weve-Gone#107]
Hello,

I tested this or can with a big modpack, but there is a issue with a mod, what I don't understand if I make a new world. The c2me and lithium is just out, because ''not enough crash'' that say. I remember that the mod can work in the world, but after pair seconds is a crash right. This I have  also by 1.19.4-1.19.2. But I have that modpack delete from modrith laucher. Was from Fabulously Optimized with some mods extra.

This is the crashraport from 1.20.1
[crash-2024-09-06_16.07.30-server.txt](https://github.com/user-attachments/files/16909298/crash-2024-09-06_16.07.30-server.txt).

I hope can you fix this problem and much succ6s.

**Comment by JT122406** [comment]
This is a incompatibility can you list all your worldgen mods/datapacks

**Comment by espressokofie** [comment]
this is alle mobs that I have:
alernate-current
ambientsounds
aquamirae
architectury
attributefix
auto-clicker
bclib
better clouds
betterend
betternether
blanket client tweaks
brrp
bygonenether
c2mc
cateyes (nightvision)
chat heads
chunky
cinderscapes
clickadv
cloth config
clumps
clutter
collectieve
conjuring
connectivity
continuity
controlling
corgilib
creativecore
cristellib
cupboard
cpm (customplayermodels)
debugify
dungeonsarise
dynamic fps
ears
eating animation
emuno
endermanoverhaul
enderzoology
endsphatasm
entityculling
essential
fabric-api
		fastasyncworldsave
		fastload
		ferritecore
		forgeconfigapiport
		fpsreducer
		freecam
		frostiful
		galosphere
		geckolib
		graveyard
		held-item-info
		iceandfire fabric 
		icterine
		idwtialsimmoedm
		illagerinvasion
		immediatelyfast
		improvedsignediting
		incendium
		indium
		inventorysorter
		jade
		jamlib
		journeymap
		krypton
		lambdynlights
		lazydfu
		leaves_us_in_peace
		litematica
		malilib
                [Let's Do] Meadow 
		memoryleakfix
		midnightlib
		minihud
		mixintrace
		mobcaptains
		modmenu
		mousetweaks
		mousewheelie
		mvs = Moog's Voyager Structures 
		natures_spirit
		notenoughcrashes
		nyctophobia
		obscure_api
		ohthetreesyoullgrow
		Improved Flame Overlays
		owo
		packetfixer
		particlerain
		phantasm
		pipeblocker:
		pistorder
		pumpkillagersquest
		puzzleslib
		reeses-sodium-options
		regions_unexplored
		resourcefulconfig
		resourcefullib
		roughlyenoughitems
		error_notifier
		searchables
		shulkerboxtooltip
		sit
		skinswapper
		smoothswapping
		sodium
		sodium-extra
		marium soulsweapons
		sound_physics_remastered
		spark
		stackrefill
		starlight
		Towns and Towers
		terrablender
		terralith
		terrestria
		thermoo
		extra thicc packets: 
		threadtweak: 
		toomanyplayers
                Towers of the Wild
                Traveler's Titles
		trinkets
		tweakeroo
		ultris
		uranus
		visuality
		vmp: Very Many Players
		Simple Voice Chat
		From The Fog
		wi_zoom
		yet_another_config_lib_
		yungsapi: YUNG's API

**Comment by JT122406** [comment]
Please try with 1.3.0 or 2.1.0 As this had compatibility changes that might close this.
Waiting 3 days for response before closing
