### ISSUE TITLE
New version for 1.21.1 fabric needs a version of corgilib that is higher than possible

### ISSUE THREAD

**Issue by Dashy22** [Potion-Studios/Oh-The-Biomes-Weve-Gone#108]
It says It needs corgilib 5.0.0.2 but the only version for 1.21.1 is 5.0.0.1 for corgilib

**Comment by JT122406** [comment]
![image](https://github.com/user-attachments/assets/fda62f1f-f18e-4385-99e6-d4379dc154a8)

**Comment by JT122406** [comment]
seems he forgot to upload it to modrinth

**Comment by CorgiTaco** [comment]
Done
