### ISSUE TITLE
1.21.1 Neoforge ver. 2.0.0 Beta Crag Gardens Generating issue

### ISSUE THREAD

**Issue by Leonxilofin** [Potion-Studios/Oh-The-Biomes-Weve-Gone#109]
I don't know if the Crag Gardens biome needs more optimizations or what but the rate it generates seems so much slower than the other biomes that you literally have to wait for it to load. 

At first I thought it was just me but it seems other in the AoE discord for the craftoria modpack seems to have t he same issue.

**Comment by CorgiTaco** [comment]
Fixed in https://github.com/Potion-Studios/Oh-The-Biomes-Weve-Gone/commit/1d95af0bb1b83a6598a02e1e524b97f9d1a08561
