### ISSUE TITLE
Cypress Anything, Especially Trees, Huge Load Times

### ISSUE THREAD

**Issue by desagas** [Potion-Studios/Oh-The-Biomes-Weve-Gone#111]
I do not have physical evidence or a log to back it up, but I can say 100% without a doubt that loading Cypress Trees in the Cypress Swamplands takes a significantly longer time to load that any other tree or biome in any mod I have seen so far in 1.21.1. Massive massive load times. However, the game server does not lag, and TPS is not bumped when this happens.

Willow trees and witch hazel trees are similar, but not as bad.

And by load, I mean generate, first time. There is no performance impact from any biomes already generated.

I am on 2.0.2-beta, with neoforge .51.

If there is anything I can do to help further, please let me know. I do not have a profiler on my system.

**Comment by JT122406** [comment]
Has this issue Persisted in the newer versions of BWG

**Comment by desagas** [comment]
I will check and report back next time I load into a world.

**Comment by desagas** [comment]
So, while it still lags a tiny amount, it does feel better. I have not tested it alone, nor have I used a profiler to see actual memory usages.

**Comment by JT122406** [comment]
Is it in new chunks or already gen chunks?

**Comment by desagas** [comment]
It only happens when generating new chunks.

**Comment by JT122406** [comment]
Hoping 782e6c17c0927cbaa18a84ba73575335d4a7cf11 will fix this for the most part
