### ISSUE TITLE
Can you just explain how the regions work?

### ISSUE THREAD

**Issue by Corjo-Disblo** [Potion-Studios/Oh-The-Biomes-Weve-Gone#113]
The title says it all. I'm trying to use this mod alongside William Wythers. I really like the individual biomes from BWG, but I prefer the overall world generation from Wythers. In combination, the BWG biomes have been dominant over WWOO and WWEE, despite BWG adding fewer biomes. I'm guessing that the regions have something to do with that, but I can't find any explanation of what the regions do anywhere. In the config, I'm not even sure if I should make the weight higher or lower if I want to reduce the effect of the regions on world generation. I wouldn't ask here, but I'm not sure where else to go with this question. Thanks.

**Comment by JT122406** [comment]
So imagine the world a section of large chunks with like 5-10 biomes per chunk, That would be a region, so in Terrablender we make those regions and fill them with our biomes so then you have a bwg region the odds of a region being choosen as the region to spawn is the weight of the region of the higher the weight of a region the more likely it is to spawn.  So in this case WW region weight is probably decently lower than ours, ours is available to change in the config I believe (Not 100% sure if this was setup yet). Does that answer your question?
