### ISSUE TITLE
1.21.1 NeoForge crash: IllegalStateException: Feature order cycle found

### ISSUE THREAD

**Issue by Daltaxy** [Potion-Studios/Oh-The-Biomes-Weve-Gone#117]
Hello, just got the issue **exception generating new chunk**
I can load into my world but it crashes (sends me back to main menu) pretty much in seconds with a "server closed"

`minecraft:old_growth_pine_taiga`
`biomeswevegone:coniferous_forest`
are mentioned in the log

latest.log: https://mclo.gs/zJuQKPz
idk why it mentions a crash report at the end; it doesn't exist.

if you need any testing or more files do not hesitate
NeoForge 21.1.54

**Comment by JT122406** [comment]
List all other Biome mods/datapacks

**Comment by Daltaxy** [comment]
Terralith
Geophilic
Biomes O' Plenty
William Wyther's Overhauled World
(Gigeresque)
many stucture mods but that probably isn't relevant?

**Comment by JT122406** [comment]
Pushing PAtch
