### ISSUE TITLE
unable to make a world

### ISSUE THREAD

**Issue by VaporeonScripts** [Potion-Studios/Oh-The-Biomes-Weve-Gone#118]
https://mclo.gs/9i2gi3R
seems to be sum with old taiga and bwg, how can i fix?
(neoforge 1.21.1, latest version of the loader)

**Comment by JT122406** [comment]
List all other Biome mods/datapacks

**Comment by VaporeonScripts** [comment]
terrablender
terralith
tectonic
Nullscape
regions-unexplored
lithostiched
William Wythers' Overhauled Overworld (tried without this but same error)
lithosphere
oh the biomes we've gone
eternal starlight

**Comment by JT122406** [comment]
It's Terralith I'm gonna look into it

**Comment by VaporeonScripts** [comment]
alright, ty

**Comment by VaporeonScripts** [comment]
tried without it, and it works! altough before it worked too, it might be the new bwg update but anyways im gonna use some other biome mode till this error gets fixed

**Comment by JT122406** [comment]
So the Fix for Slayers Beasts broke Terralith compat

**Comment by VaporeonScripts** [comment]
kinda sure

**Comment by JT122406** [comment]
Pushing Patch

**Comment by VaporeonScripts** [comment]
aight , how can i also fix the sakura_forest expanded echosphere bug?

**Comment by JT122406** [comment]
> aight , how can i also fix the sakura_forest expanded echosphere bug?

https://www.curseforge.com/minecraft/mc-mods/feature-recycler

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/c38020f2-966d-40df-9bb7-342bcf6f8239)
can confirm the new update works :D

**Comment by VaporeonScripts** [comment]
> > aight , how can i also fix the sakura_forest expanded echosphere bug?
> 
> https://www.curseforge.com/minecraft/mc-mods/feature-recycler

im using 1.21.1 neoforge, thats for 1.20.1

**Comment by JT122406** [comment]
There isn’t really a way rn
