### ISSUE TITLE
Incompatible with Creeper Overhaul.

### ISSUE THREAD

**Issue by Torathion** [Potion-Studios/Oh-The-Biomes-Weve-Gone#121]
I can't start my game, because it crashes if used with Creeper Overhaul. I think. Could also be the other way around. I use the latest version of both mods.

Crash log: https://mclo.gs/0oE4ih8
Latest log: https://mclo.gs/zlQ2OXe

**Comment by JT122406** [comment]
Not us 
Mixin apply for mod nameplate failed nameplate.mixins.json:GeoEntityRendererMixin
