### ISSUE TITLE
Suggestion: Make Flower Patches work and sound like Pink Petals

### ISSUE THREAD

**Issue by OminousDiscovery** [Potion-Studios/Oh-The-Biomes-Weve-Gone#125]
Why:  so i can mix and match the flowers I use and also for the sound pink petals just sound nicer

**Comment by JT122406** [comment]
What do you mean work like them specifically?

**Comment by OminousDiscovery** [comment]
yeah

**Comment by JT122406** [comment]
Doesn't really answer the question

**Comment by JT122406** [comment]
Closing reopen if you can answer my question by telling me what functionally you want

**Comment by SafeOfArsenal** [comment]
![image](https://github.com/user-attachments/assets/ce1ecea7-ceb2-4483-91a7-0c9850fe3030)

it would start by only placing the small flowers in the bottom right, then placing another flower on the flower block would put the flower on the top right, then placing another one would place on the top left and the another on the bottom left

**Comment by SafeOfArsenal** [comment]
oh yeah sorry for the late response and misreading the last question
