### ISSUE TITLE
Crash NeoForge 1.21.1

### ISSUE THREAD

**Issue by MrFlamazing** [Potion-Studios/Oh-The-Biomes-Weve-Gone#129]
[crash-2024-09-26_19.23.43-client.txt](https://github.com/user-attachments/files/17157094/crash-2024-09-26_19.23.43-client.txt)

**Comment by JT122406** [comment]
Not bwg mixin:APP:sodium-forge.mixins.json:ClientHooksMixin from mod sodium,pl:mixin:APP:journeymap.neoforge.mixins.json:client.ClientHooksMixin from mod
