### ISSUE TITLE
Allow the conversion of old worlds from BYG to BWG

### ISSUE THREAD

**Issue by Adidiii** [Potion-Studios/Oh-The-Biomes-Weve-Gone#131]
Title basically sums it up

**Comment by JT122406** [comment]
Not a Option That will be added as there was major changes between the mods

**Comment by Adidiii** [comment]
What changes would make this impossible? I understand that the code has changed a lot, but it's not like any blocks were removed

**Comment by JT122406** [comment]
> What changes would make this impossible? I understand that the code has changed a lot, but it's not like any blocks were removed

All the nether and end content blocks were removed, some old biomes were removed, the modid changed

**Comment by Adidiii** [comment]
It was written that the Nether and End content would be added sometime in the future. Would this be possible once those are added? As for the old biomes that were removed, did any of their blocks get removed as well? If not, the old biomes could just be converted into a newer equivalent. The modid changing shouldn't be too much of an issue, it simply involves changing it for all the other blocks.

**Comment by JT122406** [comment]
Nether and End content will not be added in the future they will be in separate mods if we do decide to add them and yes other blocks were removed:
https://github.com/Potion-Studios/BYG/discussions/1203
