### ISSUE TITLE
Overgrown stone/dacite not spreading

### ISSUE THREAD

**Issue by gnarlystarships** [Potion-Studios/Oh-The-Biomes-Weve-Gone#133]
When I played on a 1.19.2 server with _Oh The Biomes You'll Go_ mod, overgrown stone spread to other stone like grass. Now I am playing in a 1.20.1 server with _Oh The Biomes We've Gone_ and it no longer does this. Overgrown stone will not spread to other stone blocks and the same is true of the dacite variant. 
Is this a bug, or is it intentional? And if it is intentional is there any way to spread or create more overgrown stone/dacite? I tested with bone meal and that does not make it spread either.

**Comment by JT122406** [comment]
They should spread in bwg I will take a look myself and see what is going on here
