### ISSUE TITLE
[BUG] World Crash on BWG Hanging Sign Placement

### ISSUE THREAD

**Issue by heybluejay** [Potion-Studios/Oh-The-Biomes-Weve-Gone#135]
When placing a BWG hanging sign, the game crashes. I have tried with a few different varieties of sign. I encountered this in Creative mode, but have not yet attempted to place a sign in Survivor mode.. no materials yet :)

Error message:
The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: Invalid block entity biomeswevegone:hanging_sign // net.potionstudios.biomeswevegone.world.level.block.entities.sign.BWGHangingSignBlockEntity state at class_2338{x=33, y=-58, z=1}, got Block{biomeswevegone:aspen_wall_hanging_sign}[facing=south,waterlogged=false]

Thanks!

**Comment by JT122406** [comment]
What platform?, Also what Version of mc and the mod

**Comment by JT122406** [comment]
Pushing 2.1.3 for Forge and Fabric to Address this issue

**Comment by heybluejay** [comment]
Windows/Java! My bad 😊
