### ISSUE TITLE
Exception Access Violation incompatibility with Pokecube mod.

### ISSUE THREAD

**Issue by Keltas** [Potion-Studios/Oh-The-Biomes-Weve-Gone#136]
Hello, I am getting a crash on worldgen when using the mod together with the Pokecube mod. I've created a new instance in Curseforge mod manager with Minecraft 1.20.1 Forge version 47.3.0. Next I've installed OTBWG (version 1.3.1) and let Curseforge install its requirements as well as Pokecube AIO (version 3.24.0.k). On creating new world the game crashes with exception access violation. I've attached the logs below.
[hs_err_pid1852.log](https://github.com/user-attachments/files/17306146/hs_err_pid1852.log)
[latest.log](https://github.com/user-attachments/files/17306149/latest.log)

**Comment by JT122406** [comment]
Issue comes from our EatBlockGoalMixin (This is a note for me)

**Comment by JT122406** [comment]
Correction this is a out of memory error just give java more ram
