### ISSUE TITLE
Slow to generate new chunks in BWG biomes

### ISSUE THREAD

**Issue by Deathwolf01** [Potion-Studios/Oh-The-Biomes-Weve-Gone#139]
Server: 1.20.1
Forge 47.3.11

Basalt Barrera and one of the Badlands BWG biomes keeps freezing and crashing my server even if I am the only one on the server (temp solution was to disable max tick time in server.properties). I did a test removing BWG and the chunk coordinates with freezing issues loaded normally again. I noticed other tickets regarding similar experiences with other BWG biomes. If there is anything you'd like for me to help test let me know. These chunks do load but very slowly, maybe 1-2 chunks per 30 seconds or 1 minute. And my server specs are really decent, server has 48Gb allocated but only goes up to 20Gb usually, no memory leak detected.
![image](https://github.com/user-attachments/assets/c61f2d56-05a2-44f2-b431-6035f223d0b7)

I have the following versions:
Oh-The-Biomes-Weve-Gone-Forge-1.3.3
Oh-The-Trees-Youll-Grow-forge-1.20.1-1.3.1
Feature-Recycler-forge-1.0.1.jar

**Comment by JT122406** [comment]
Can you send the crash log

**Comment by Deathwolf01** [comment]
I have done lots of testing and am no longer getting the crash issue. I believe it was arclight that was having some async thread issue. Switching to Mohist has stopped the server from crashing. However the same slow loading of new chunks.
![image](https://github.com/user-attachments/assets/893b4973-d8a5-4fc5-8657-a6e81e257187)

However, I do not believe this is an issue with your mod. I had thought it was previously, but this slow chunk loading appears to also affect other biomes too far away from any BWG biomes. I think we can close this ticket as I no longer have sufficient evidence of this issue being caused by BWG.
