### ISSUE TITLE
Incompatibility with slayers beasts (Temp Solution: Use Feature Recycler)

### ISSUE THREAD

**Issue by glorification12** [Potion-Studios/Oh-The-Biomes-Weve-Gone#14]
Im no expert but it seems like howling peaks from BWG and eucalyptus forest from slayers beast dont like eachother very much

latestlog + crashlog (mclogs was tweaking sorry)

LL: https://pastebin.com/WZK7WwyH

CL: https://pastebin.com/cgQE63c2

**Comment by CorgiTaco** [comment]
Temporary solution is to use: https://www.curseforge.com/minecraft/mc-mods/feature-recycler

**Comment by JT122406** [comment]
closed in #82
