### ISSUE TITLE
[1.20.1 - NeoForge] man o war wont go in bucket 

### ISSUE THREAD

**Issue by Jadedragon10121** [Potion-Studios/Oh-The-Biomes-Weve-Gone#144]
as the title says, i am using 1.20.1 neoforge

**Comment by JT122406** [comment]
I have tested and can replicate the issue only on NeoForge and Not Forge, I will look into it but it may be a missing patch or something on Neo

**Comment by JT122406** [comment]
Dug into this, Nothing I can see from our side just remember only Baby ManOwars can be put in buckets, I tested and the baby ones work correctly on NeoForge from my testing
