### ISSUE TITLE
Crag Gardens are super slow to generate

### ISSUE THREAD

**Issue by legomaniac89** [Potion-Studios/Oh-The-Biomes-Weve-Gone#146]
Every other biome generates as normal, but crag gardens will take 2-3 minutes to generate a single chunk. 2.1.5 fabric

**Comment by JT122406** [comment]
Fixed in https://github.com/Potion-Studios/Oh-The-Biomes-Weve-Gone/commit/1d95af0bb1b83a6598a02e1e524b97f9d1a08561

**Comment by JT122406** [comment]
Just haven't pushed a release yet
