### ISSUE TITLE
Bug/World Gen Optimize world from 1.9.4 to 1.20.1 dont work

### ISSUE THREAD

**Issue by Philip2777** [Potion-Studios/Oh-The-Biomes-Weve-Gone#147]
World Gen / Optimize world from 1.9.4 to 1.20.1

I have the problem that Minecraft reports a faulty world when I want to optimize / update the world from Minecraft version 1.9.4 to 1.20.1.

Before that I only played with Oh The Biomes You'll Go. Updating a map to a newer version was always possible.

How do I update the map from 1.9.4 to 1.20.1?

Is this error / bug already known?

or is it not possible at all?

**Comment by JT122406** [comment]
Tis is not At all possible due to the massive backend changes and changes to the modid
