### ISSUE TITLE
 server not able to shutdown with this mod and or this mods dependencies

### ISSUE THREAD

**Issue by OpticBlitz** [Potion-Studios/Oh-The-Biomes-Weve-Gone#148]
server runs fine and is able to stop/restart. with mod installed, server is unable to stop/restart.

**Comment by JT122406** [comment]
If possible can you try to narrow down if it is us or one of the dependencies

**Comment by CeeVeeR** [comment]
I am also facing this issue, I am pregenerating a world with chunky, my server.properties have synchronous writing enabled. 
Is there any suggested way to narrow down chunk saving? my console doesnt report anything.
I will only use OTBWG and report back if its the single cause or a combination of world gen mods and or chunky

**Comment by CeeVeeR** [comment]
> I am also facing this issue, I am pregenerating a world with chunky, my server.properties have synchronous writing enabled. Is there any suggested way to narrow down chunk saving? my console doesnt report anything. I will only use OTBWG and report back if its the single cause or a combination of world gen mods and or chunky

OTBWG doesn't seem to be the issue, disabling it resulted in chunk saving still freezing or crashing. This is unrelated to OTBWG on my server. The cause could be Terralith, Tectonic in a combination of optimization mods. BOP and other world generation mods are excluded. the YUNG's series is part of the equation

**Comment by CorgiTaco** [comment]
this is probably related to: https://github.com/CorgiTaco/CorgiLib/issues/53

**Comment by JT122406** [comment]
Going to close here As I believe it is CorgiLib

**Comment by MimzyFang** [comment]
@OpticBlitz the isssue has been fixed update CorgiLib and it will be gone

**Comment by CorgiTaco** [comment]
Correct
