### ISSUE TITLE
Getting empty biome named as deferred_placeholder

### ISSUE THREAD

**Issue by md500** [Potion-Studios/Oh-The-Biomes-Weve-Gone#15]
It loads an empty biome as shown in the images.

Using BetterMC BMC2 Fabric version.
Log: https://mclo.gs/RWEX8H9
Config of BWG: https://mclo.gs/FGrmuVp

![image](https://github.com/user-attachments/assets/c65bdfb3-39a9-4121-9e49-787473e7aca6)
![image](https://github.com/user-attachments/assets/0498a953-cd96-4664-86a1-13a92a325a1c)
![image](https://github.com/user-attachments/assets/ae3ec8d3-4f9e-4590-87bf-695a26c37211)

**Comment by CorgiTaco** [comment]
You'll need to find the conflict here, this isn't BWG doing this itself but a combo of mods

**Comment by truswo** [comment]
I found the mod conflicting here, it seems like Promenade created a incompatibility with Biomes We've Gone after changing from Terrablender to Biolith in v4.1.0 [(Promenade Issue)](https://github.com/DawnTeamMC/Promenade/issues/188). This can be resolved by updating Biolith to a newer version (or by just downgrading Promenade to v4.0.0)
