### ISSUE TITLE
[1.20.1 fabric] BWGv1.4.0 - Skyrise_vale Village causing crash

### ISSUE THREAD

**Issue by AOESh2o** [Potion-Studios/Oh-The-Biomes-Weve-Gone#155]
Skyrise_vale village making the game mostly crash instantly or in the 3sec after seing it.
Version 1.20.1 fabric, 1.4.0 BWG
Log:

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2024-11-03 16:24:31
Description: Exception ticking world

java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "this.fruitBlock" is null
	at knot//net.potionstudios.biomeswevegone.world.level.block.plants.tree.leaves.BWGFruitLeavesBlock.method_9514(BWGFruitLeavesBlock.java:32)
	at knot//net.minecraft.class_4970$class_4971.method_26199(class_4970.java:1117)
	at knot//net.minecraft.class_3218.redirect$doe000$lithium$redirectBlockStateTick(class_3218.java:10743)
	at knot//net.minecraft.class_3218.method_18203(class_3218.java:523)
	at knot//net.minecraft.class_3215.method_14161(class_3215.java:382)
	at knot//net.minecraft.class_3215.method_12127(class_3215.java:326)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:333)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:105)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at knot//net.potionstudios.biomeswevegone.world.level.block.plants.tree.leaves.BWGFruitLeavesBlock.method_9514(BWGFruitLeavesBlock.java:32)
	at knot//net.minecraft.class_4970$class_4971.method_26199(class_4970.java:1117)
	at knot//net.minecraft.class_3218.redirect$doe000$lithium$redirectBlockStateTick(class_3218.java:10743)
	at knot//net.minecraft.class_3218.method_18203(class_3218.java:523)
	at knot//net.minecraft.class_3215.method_14161(class_3215.java:382)
	at knot//net.minecraft.class_3215.method_12127(class_3215.java:326)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:333)

-- Affected level --
Details:
	All players: 1 total; [class_3222['AOES1'/66, l='ServerLevel[Nouveau monde]', x=1832.47, y=87.57, z=695.26]]
	Chunk stats: 4780
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,78,0), Section: (at 0,14,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 900 game time, 449 day time
	Level name: Nouveau monde
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 145123 (now: false), thunder time: 137377 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:105)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 799137752 bytes (762 MiB) / 2936012800 bytes (2800 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon RX 6750 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x73df
	Graphics card #0 versionInfo: DriverVersion=32.0.12019.1028
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 38826.85
	Virtual memory used (MB): 25172.40
	Swap memory total (MB): 22528.00
	Swap memory used (MB): 735.90
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx8192m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		ad_astra: Ad Astra 1.15.18
			javazoom_jlayer: jlayer 1.0.1
		antiquelegacy: Epic Knights: Antique Legacy 1.8
		aquamirae: Aquamirae 6
		architectury: Architectury 9.2.14
		ati_structures_fabric: ati_structures_fabric 1.1.0
		badoptimizations: BadOptimizations 2.2.0
		bclib: BCLib 3.0.14
			wunderlib: WunderLib 1.1.5
		beansbackpacks: BeansBackpacks 2.0
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.3
			org_reflections_reflections: reflections 0.10.2
		betterend: Better End 4.0.11
		betterendisland: YUNG's Better End Island 1.20-Fabric-2.0.6
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.6
		betterfpsdist: Better FPS distance Mod 1.20.1-6.0
		betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.5
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betternether: Better Nether 9.0.10
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0.3
		biomeswevegone: Oh The Biomes We've Gone 1.4.0
		bloomingnature: [Let's Do] BloomingNature 1.0.9
		botarium: Botarium 2.3.4
			team_reborn_energy: Energy 3.0.0
		chas: Craftable Horse Armour & Saddle 1.20
		clean-debug: Clean F3 0.4.8
		cloth-config: Cloth Config v11 11.1.136
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.4
		corgilib: CorgiLib 4.0.3.2
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		coroutil: CoroUtil 1.20.1-1.3.7
			forgeconfigapiport: Forge Config API Port 8.0.0
		create: Create 0.5.1-f-build.1417+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.10-2
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_brewing: Porting Lib Brewing 2.3.2+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.2+1.20.1
			porting_lib_models: Porting Lib Models 2.3.2+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.2+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.2+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		create_enchantment_industry: Create Enchantment Industry 1.2.16
			create_dragon_lib: Create Dragon Lib 1.4.2
		createaddition: Create Crafts & Additions 1.2.4
		createbigcannons: Create Big Cannons 5.5.1+mc.1.20.1-fabric
			ritchiesprojectilelib: Ritchie's Projectile Library 2.0.0-dev+mc.1.20.1-fabric-build.182
				porting_lib_utility: Porting Lib Utility 2.1.1127+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1127+1.20
		cristellib: Cristel Lib 1.1.5
			blue_endless_jankson: jankson 1.2.3
		cupboard: cupboard 1.20.1-2.7
		doapi: [Let's Do] API 1.2.15
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		endermanoverhaul: Enderman Overhaul 1.0.4
		ends_delight: End's Delight 2.1
			porting_lib_config: Porting Lib Config 2.3.4+1.20.1
				porting_lib_core: Porting Lib Core 2.3.4+1.20.1
		entityculling: EntityCulling 1.7.1
		expanded_ecosphere: Expanded Ecosphere 3.2.4
		expandeddelight: Expanded Delight 0.3.2
			mm: Manningham Mills 2.3
			omega-config: OmegaConfig 1.4.0+1.20.1
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabricloader: Fabric Loader 0.16.7
			mixinextras: MixinExtras 0.4.1
		farmersdelight: Farmer's Delight 1.20.1-2.1.6+refabricated
			porting_lib_accessors: Porting Lib Accessors 2.3.4+1.20.1
			porting_lib_base: Porting Lib Base 2.3.4+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.4+1.20.1
				porting_lib_common: Porting Lib Common 2.3.4+1.20.1
				porting_lib_entity: Porting Lib Entity 2.3.4+1.20.1
				porting_lib_extensions: Porting Lib Extensions 2.3.4+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.4+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.4+1.20.1
				porting_lib_transfer: Porting Lib Transfer 2.3.4+1.20.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.4+1.20.1
			porting_lib_loot: Porting Lib Loot 2.3.4+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.4+1.20.1
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 2.3.4+1.20.1
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.4+1.20.1
		featurerecycler: Feature Recycler 1.0.1
		ferritecore: FerriteCore 6.0.1
		galosphere: Galosphere 1.20.1-1.4.1
		geckolib: GeckoLib 4 4.4.9
			com_eliotlash_mclib_mclib: mclib 20
		gpumemleakfix: Gpu memory leak fix mod 1.20.1-1.8
		guardvillagers: GuardVillagers 2.0.9-1.20.1
			midnightlib: MidnightLib 1.4.1
		iceandfire: Ice And Fire 0.6.5
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			fabric-trade-api: Fabric Trade API 0.1.2
		immediatelyfast: ImmediatelyFast 1.3.1+1.20.4
			net_lenni0451_reflect: Reflect 1.3.4
		immersive_aircraft: Immersive Aircraft 1.1.2+1.20.1
			org_mariuszgromada_math_mathparser_org-mxparser: MathParser.org-mXparser 5.2.1
		immersive_weathering: Immersive Weathering 1.20.1-2.0.3
		indium: Indium 1.0.34+mc1.20.1
		iris: Iris 1.7.5+mc1.20.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		jade: Jade 11.11.0+fabric
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.20.0.105
		jupiter: Jupiter 2.0-alpha4
		lithium: Lithium 0.11.2
		loadmychunks: Load My Chunks 1.0.6-hf2
		magistuarmory: Epic Knights Mod 9.16
		magistuarmoryaddon: Epic Knights: Addon 1.10
		man_of_many_planes: Man of Many Planes 0.2.0+1.20.1
		medieval_buildings: Medieval Buildings 1.0.1
		memoryleakfix: Memory Leak Fix 1.1.5
		minecraft: Minecraft 1.20.1
		modernfix: ModernFix 5.19.4+mc1.20.1
		moonlight: Moonlight 1.20-2.13.21
		mr_lithosphere: Lithosphere 1.2
		musketmod: Musket Mod 1.5.4
		naturalist: Naturalist 4.0.3
		natures_spirit: Nature's Spirit 1.6.3-1.20.1
		naturescompass: Nature's Compass 1.20.1-2.2.3-fabric
		nethersdelight: Nether's Delight Refabricated 1.20.1-4.1.1
		nullscape: Nullscape 1.2.7
		obscure_api: Obscure API 16
		ohthetreesyoullgrow: Oh The Trees You'll Grow 1.20.1-1.3.1
		player-animator: Player Animator 1.0.2-rc1+1.20
		presencefootsteps: Presence Footsteps 1.9.4+1.20.1
			kirin: Kirin UI 1.15.6+1.20.1
		railways: Create: Steam 'n' Rails 1.6.4+fabric-mc1.20.1
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.1-build.101
		regions_unexplored: Regions Unexplored 0.5.6+1.20.1
		resourcefulconfig: Resourcefulconfig 2.1.2
		resourcefullib: Resourceful Lib 2.1.29
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		ribbits: Ribbits 1.20.1-Fabric-3.0.0
		servercore: ServerCore 1.5.1+1.20.1
			fabric-permissions-api-v0: fabric-permissions-api 0.3.1
			org_yaml_snakeyaml: snakeyaml 2.2
			placeholder-api: Placeholder API 2.1.3+1.20.1
			space_arim_dazzleconf_dazzleconf-core: dazzleconf-core 1.3.0-M2
			space_arim_dazzleconf_dazzleconf-ext-snakeyaml: dazzleconf-ext-snakeyaml 1.3.0-M2
		slavicarmory: Epic Knights: Slavic Armory 1.5
		smallships: Small Ships 2.0.0-b1.4
		smoothchunk: Smooth chunk save Mod 1.20.1-3.6
		smwyg: Show Me What You Got 1.1.1
		sodium: Sodium 0.5.11+mc1.20.1
		sodium-extra: Sodium Extra 0.5.4+mc1.20.1-build.115
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		sodiumdynamiclights: Sodium Dynamic Lights 1.0.9
		sodiumextras: Sodium Extras 1.0.5
		sodiumoptionsapi: Sodium Options API 1.0.5
			mixinsquared: MixinSquared 0.2.0-beta.6
		spark: spark 1.10.53
		storagedrawers: Storage Drawers 12.10.1
		structureessentials: Structure Essentials Mod 1.20.1-3.4
		t_and_t: Towns and Towers 1.12
		tectonic: Tectonic 2.4.1b
		terrablender: TerraBlender 3.0.1.7
		timecontrol: TimeControl 1.6.0
		uranus: Uranus 1.7.1
			sponsor_core: Sponsor Core 1.0.0
		uselessreptile: Useless Reptile 0.7.4-1.20.1
			common-protection-api: Common Protection API 1.0.0
			primitive_multipart_entities: Primitive Multipart Entities 1.1.1
		watut: What Are They Up To 1.20.1-1.1.3
		wwoo: William Wythers' Overhauled Overworld 2.0.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.1+1.20.1-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yungsapi: YUNG's API 1.20-Fabric-4.0.6
			org_javassist_javassist: javassist 3.29.2-GA
		yungscavebiomes: YUNG's Cave Biomes 1.20.1-Fabric-2.0.0
	Loaded Shaderpack: ComplementaryReimagined_r5.2.2.zip
		Profile: MEDIUM (+2 options changed by user)
	Flywheel Backend: Off
	Server Running: true
	Player Count: 1 / 8; [class_3222['AOES1'/66, l='ServerLevel[Nouveau monde]', x=1832.47, y=87.57, z=695.26]]
	Data Packs: vanilla, fabric, natures_spirit:modified_badlands, natures_spirit:modified_birch_forest, natures_spirit:modified_windswept_hills, natures_spirit:modified_jungle, natures_spirit:modified_savannas, natures_spirit:modified_dark_forest, natures_spirit:modified_desert, natures_spirit:modified_flower_forest, natures_spirit:modified_mountain_biomes, natures_spirit:modified_swamp, resources/ee_default (incompatible), resources/ee_remove_blobs (incompatible), Moonlight Mods Dynamic Assets, Immersive Weathering Generated Pack, tectonic/tectonic
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.16.7-1.20.1

**Comment by JT122406** [comment]
This has been fixed see issues #153
