### ISSUE TITLE
Incompatibility with Botany Pots 

### ISSUE THREAD

**Issue by FlamingInk** [Potion-Studios/Oh-The-Biomes-Weve-Gone#156]
Noticed that the White and Yellow Sakura Saplings aren't compatible with the Botany Pots mod. Gives saplings and sticks but no logs, so when its supposed to give a log the sapling stops at the last grow cycle
![botany pot incompat](https://github.com/user-attachments/assets/700669d3-b620-4f88-b50c-d75a41e7c63a)

**Comment by JT122406** [comment]
Most likely this is going to be something that gets fixed on their side

**Comment by JT122406** [comment]
Confirmed with dev that it is an issue on there side
