### ISSUE TITLE
Trees casually break bedrock

### ISSUE THREAD

**Issue by Zeykehasnt** [Potion-Studios/Oh-The-Biomes-Weve-Gone#157]
Tree trunks calmly destroy everything in their way.

![image](https://github.com/user-attachments/assets/eb5dce03-6149-4360-9bcb-91bfc5dadd6e)

**Comment by JT122406** [comment]
What Trees you'll grow version are you using as this was patched

**Comment by Zeykehasnt** [comment]
Forge 1.20.1 1.3.0

**Comment by JT122406** [comment]
It seems the version 1.3.1 hasn't been published yet

**Comment by JT122406** [comment]
1.3.1 has now been published to CurseForge with a fix for this
