### ISSUE TITLE
Incompatibility with William Wythers' Expanded Ecosphere (Temp Solution: Use Feature Recycler)

### ISSUE THREAD

**Issue by SimulationOfMario** [Potion-Studios/Oh-The-Biomes-Weve-Gone#16]
When I start the game with both mods, it doesn't crash.
But I tried to create a new world and this is the crash log it gave me:
[crash-2024-07-29_12.44.13-client.txt](https://github.com/user-attachments/files/16411606/crash-2024-07-29_12.44.13-client.txt)

After removing WWEE, the world did create and I think everything is fine now.

**Comment by CorgiTaco** [comment]
Temporary solution is to use: https://www.curseforge.com/minecraft/mc-mods/feature-recycler

**Comment by sugan-reden** [comment]
Hi!
Just had this crash today that seems related, so  I thought I'd bump this up.
Not sure if it's necessary but, just in case, here's an additional crash log : https://gist.github.com/sugan-reden/ec7754ca3f998f55441cb2689d0017b1
Keep up the good work! And take care <3

**Comment by JT122406** [comment]
Posting this for me:
Feature 'minecraft:patch_melon_sparse'
  must be before 'biomeswevegone:oak_bushes' (defined in 'biomeswevegone:fragment_jungle' at index 8, 9)
  must be before 'biomeswevegone:mushrooms' (defined in 'biomeswevegone:coconino_meadow' at index 13, 22 and 8 others)
  must be before 'minecraft:seagrass_normal' (defined in 'biomeswevegone:crag_gardens' at index 11, 12)
  must be before 'minecraft:sea_pickle' (defined in 'biomeswevegone:lush_stacks' at index 10, 11)
  must be before 'minecraft:patch_melon_sparse' (defined in 'minecraft:warm_ocean' at index 11, 12)
