### ISSUE TITLE
orchard trees are __STILL__ not dropping apples, no matter the version.

### ISSUE THREAD

**Issue by 20Tigerpaw** [Potion-Studios/Oh-The-Biomes-Weve-Gone#162]
good day, 
ive used every version of BWG that mentioned fixing the apple drops, but its still not working for me for some reason.  1.0.3 crashes with HTtreechop, 1.0.5 works but no apples, and 1.4.1 dosent drop apples either. also ive tried the 1.21 version and still no apples. its not HTTC as that works with BYG just fine.
i see that the code SAYS it should work, but either my pc dosent want to load the code properly, or this bug keeps coming back to haunt you guys. ive tried a MC install free from all mods minus BWG and HTTC, tried using fortune on the leaves AND on the tree, tried letting the leaves break on their own, tried 1.0.3, 1.0.4, 1.0.5, and still nothing...
and not to be "that guy" but if you do manage to fix this could you make a 1.20.1 patch for it please? the 1.20,1 modpack ive been working on is finished i just cant enjoy it without my apple pie...

**Comment by JT122406** [comment]
Is this happening on both loaders?

**Comment by 20Tigerpaw** [comment]
> Is this happening on both loaders?

ive only tested on fabric, as thats what my modpack is running, before i post this ill test forge 1.20.1 and 1.21.1.
1.20.1: no apples at all. even with fortune and letting leaves decay.
1.21.1: HTtreechop isnt updated yet, so i could only let leaves decay and break them with fortune: no apples from either method.

**Comment by JT122406** [comment]
So I want to be clear this only has to do with the leaves and not the physical apple block? So breaking the leaves don't drop apples unless there is a apple below? or even when it is below.

**Comment by 20Tigerpaw** [comment]
> So I want to be clear this only has to do with the leaves and not the physical apple block? So breaking the leaves don't drop apples unless there is a apple below? or even when it is below.

havent tested with the apple fruit, but the apple LEAF(not just orchard leaf) isnt dropping a apple on break or decay. unlike BYG which did drop one.(loaded up a modpack with BYG to confirm)
tested the apple FRUIT before i posted this: the apple FRUIT (from bonemeal) does drop if the apple LEAF above it is broken.

**Comment by JT122406** [comment]
> > So I want to be clear this only has to do with the leaves and not the physical apple block? So breaking the leaves don't drop apples unless there is a apple below? or even when it is below.
> 
> havent tested with the apple fruit, but the apple LEAF(not just orchard leaf) isnt dropping a apple on break or decay. unlike BYG which did drop one.(loaded up a modpack with BYG to confirm) tested the apple FRUIT before i posted this: the apple FRUIT (from bonemeal) does drop if the apple LEAF above it is broken.

We did change some mechanics around this in BWG compared to BYG so fruit under leaves when you break them only drop if the fruit under them is full age or if not about half the time otherwise.  This is during Leaf decay, and then for just the ripe leaves we require silk touch or shears with fortune to even have a chance at getting a fruit to drop and that chance is below %4.  So you may just be seeing expected behavior as we made this change to make more sense as really fruit should only be dropping from leaves if there is a fruit below the leaves

**Comment by 20Tigerpaw** [comment]
fruits arnt spawning with the tree at all though, either by worldgen or by bonemeal(on the sapplings) the one time there is fruit is when i manually bonemeal the apple leaf. 
i decided to load the world and set the random tick speed to 20000, no apple fruits grew from the trees after 5 minutes, flowering leaves did change to apple leaves though.

not to be rude, but the biome all about apples now making it hard to get apples seems... counterintuitive? it just makes regular old oak trees are a better source of apples and logs.
(tested before comment, HTtreechop does give apples with regular oak trees, but not with BWG orchard trees)

**Comment by JT122406** [comment]
@20Tigerpaw Are you in our discord, just I think having this convo in there might be easier just give me a ping

**Comment by JT122406** [comment]
Fixed in last few commits
