### ISSUE TITLE
[Feature Request] Improving and adding more interactions with hanging fruit 

### ISSUE THREAD

**Issue by Zeykehasnt** [Potion-Studios/Oh-The-Biomes-Weve-Gone#163]
Here are some ideas on how to make them more interesting. 
1. Change their models to cubic to replace the weird and extremely large cross models. While making their collision solid and the same as the model.
2. Add projectile interaction as shown in the video. This will be handy as orchard trees for example are quite large and hard to reach. https://youtu.be/FDG0EixeSWo
3. The fruit should completely disintegrate when harvested, rather than returning to stage 0.
4. "Fruiting foliage" must have the tag can_grow_fruits(sculk shrieker is an example of this) , to be able to put working foliage in creative mode. 

![javaw_fKnLBeNpQh](https://github.com/user-attachments/assets/861990ea-a33c-4baf-842c-4961afb08118)
![javaw_HDpkwp1GtI](https://github.com/user-attachments/assets/ba3f96e5-4f1e-4e03-be65-67e47e42a914)
![image](https://github.com/user-attachments/assets/026d8f6a-07fb-49f6-b755-9c08fe6de33c)
![javaw_F8ydZVVJX8](https://github.com/user-attachments/assets/905bdb82-98c9-4aab-8473-70b7298f73e4)
![javaw_14LP9MmoNC](https://github.com/user-attachments/assets/25d825eb-0e88-447e-a2bf-bcb19a0c9da0)
![image](https://github.com/user-attachments/assets/9a2d1c4b-0430-4a60-b34b-874e6efdb064)

Apple models - [Fancy_apples.zip](https://github.com/user-attachments/files/17774168/Fancy_apples.zip)

**Comment by Zeykehasnt** [comment]
![image](https://github.com/user-attachments/assets/12641e49-7d95-421e-b4d0-a31f08ff1fbc) 
![image](https://github.com/user-attachments/assets/3aff19d3-f221-4813-9cac-a183cb22467d)
![image](https://github.com/user-attachments/assets/1fe76f65-f2ff-4f57-8c88-7d2bc0ac81d4)
![image](https://github.com/user-attachments/assets/5a75d594-2054-4028-9454-41c95c00b51a)

[Fancy_apples.zip](https://github.com/user-attachments/files/17744905/Fancy_apples.zip)

For logic, the fruit block should be destroyed completely when harvested, rather than returning to stage 0.

**Comment by JT122406** [comment]
So we aren't going to do the models as it doesn't match our mod style however feel free to make a texture pack to do that,
I added projectile interactions in 7efe581aca2dcf1d58cdb12a512b370983ccd2ac
Returning to stage 0 is common across farming mods which is why we do it, it makes it easy to farm and makes sense when you look at the first state it's the stem and you pick the fruit by hand the stem/branch would be left.
The last suggestion I'm still thinking about as I think it would be useful but the block and item are separate things in our mod

**Comment by JT122406** [comment]
The last suggestion is implemented in our own way in the last commits
