### ISSUE TITLE
Incompatibility with Organics

### ISSUE THREAD

**Issue by MrHimera** [Potion-Studios/Oh-The-Biomes-Weve-Gone#164]
Oh The Biomes We've Gone 1.20.1 1.4.2
TerraBlender 1.20.1 3.0.1.7
Organics 1.20.1 0.1.9

When creating a world, the game crashes. This happens when the Organics mod is installed.

Log: https://pastebin.com/2FyWMstF
Crash Report: https://pastebin.com/JnmvvRSn

**Comment by JT122406** [comment]
IS this reported to Both us and Organics?

**Comment by MrHimera** [comment]
> IS this reported to Both us and Organics?

They don't have GitHub, so I left a comment on the Organics mod itself.
I also wrote to them on Discord.

**Comment by JT122406** [comment]
Posting Feature Log:
Feature 'minecraft:flower_default'
  must be before 'minecraft:patch_grass_badlands' (defined in 'minecraft:ice_spikes' at index 2, 3 and 21 others)
  must be before 'minecraft:patch_grass_forest' (defined in 'biomeswevegone:cika_woods' at index 1, 2 and 2 others)
  must be before 'minecraft:bamboo_light' (defined in 'organics:hoaky_forest' at index 0, 1)
  must be before 'minecraft:flower_default' (defined in 'biomeswevegone:jacaranda_jungle' at index 3, 4)

**Comment by JT122406** [comment]
Issue has been patched, There is one thing Organics doesn't use Terrablender so where biomes spawn might be odd sometimes but that's on them.
