### ISSUE TITLE
Biome IDs

### ISSUE THREAD

**Issue by UsernameGeri** [Potion-Studios/Oh-The-Biomes-Weve-Gone#166]
This is not an issue, but I don't want to give my phone number to ask on Discord.

Basically I would just like to ask for a full list of biome IDs so I can add support for my custom sky pack.

Thanks!

**Comment by CorgiTaco** [comment]
https://github.com/Potion-Studios/Oh-The-Biomes-Weve-Gone/blob/1.21.1/Common/src/main/java/net/potionstudios/biomeswevegone/world/level/levelgen/biome/BWGBiomes.java#L28

**Comment by UsernameGeri** [comment]
Thanks. So I guess a full ID would look something like this: `"bwg:allium_shrubland"` for example?

**Comment by CorgiTaco** [comment]
@UsernameGeri `biomeswevegone:<biome_id>`
