### ISSUE TITLE
incompatibility with "excessive building"

### ISSUE THREAD

**Issue by venomgeiser** [Potion-Studios/Oh-The-Biomes-Weve-Gone#168]
hello, everytime that i try to load these two mods together (excessive building and bwg) this crash screen appears

[crash-2024-11-20_21.20.39-server.txt](https://github.com/user-attachments/files/17838312/crash-2024-11-20_21.20.39-server.txt)

i'm not sure wich mod is causing this issue since bwg has a lot of incompatibility issues, so i'm posting this on both github pages.

**Comment by JT122406** [comment]
Feature 'minecraft:flower_default'
  must be before 'minecraft:patch_grass_normal' (defined in 'minecraft:windswept_savanna' at index 2, 3)
  must be before 'minecraft:patch_sunflower' (defined in 'biomeswevegone:coconino_meadow' at index 3, 4)
  must be before 'minecraft:trees_plains' (defined in 'minecraft:sunflower_plains' at index 2, 3)
  must be before 'minecraft:flower_plains' (defined in 'minecraft:dripstone_caves' at index 2, 3 and 5 others)
  must be before 'minecraft:patch_grass_plain' (defined in 'minecraft:dripstone_caves' at index 3, 4 and 5 others)
  must be before 'minecraft:flower_default' (defined in 'excessive_building:snowy_maple_forest' at index 4, 5 and 1 others)

**Comment by JT122406** [comment]
Did some testing bug seems to only be in the forge version

**Comment by CorgiTaco** [comment]
@venomgeiser temp fix: https://www.curseforge.com/minecraft/mc-mods/feature-recycler

**Comment by venomgeiser** [comment]
It worked! thank you very much guys
