### ISSUE TITLE
Can't craft special crafting tables (1.20.1 forge)

### ISSUE THREAD

**Issue by ivxvm** [Potion-Studios/Oh-The-Biomes-Weve-Gone#169]
I can't craft for example "florus crafting table", because when I put 4 florus planks into the grid, it crafts vanilla crafting table. I guess that's because florus planks have tag "#minecraft:planks". Any fixes to this?

**Comment by CorgiTaco** [comment]
@ivxvm https://www.curseforge.com/minecraft/mc-mods/polymorph
