### ISSUE TITLE
Exception generating new chunk (Temp Solution: Use Feature Recycler)

### ISSUE THREAD

**Issue by wolf886** [Potion-Studios/Oh-The-Biomes-Weve-Gone#17]
minecraft opened fine but when i went to create new world it crashed

Ive got a lot of mods added so i dont know what the issue is sorry! :C 

it said it was the sakura_grove? 

[crash-2024-07-29_20.55.56-server.txt](https://github.com/user-attachments/files/16411588/crash-2024-07-29_20.55.56-server.txt)

**Comment by md500** [comment]
Try disabling the biome changing:

`"biomeswevegone:sakura_grove": true`

to

`"biomeswevegone:sakura_grove": false`

in `<you instance>\.minecraft\config\biomeswevegone\world_generation.json5`

Save the changes, and reload you world.

I had the same issue with BetterMC BMC2 Fabric, and i had to disable `biomeswevegone:sakura_grove` and `biomeswevegone:araucaria_savanna` too

**Comment by wolf886** [comment]
ok ill try that and see what happens. thank you!

**Comment by CorgiTaco** [comment]
Temporary solution is to use: https://www.curseforge.com/minecraft/mc-mods/feature-recycler

**Comment by JT122406** [comment]
Do we know what the conflicting mod is

**Comment by JT122406** [comment]
Also @wolf886 If possible please try with 1.1.1-Beta of BWG and https://modrinth.com/mod/cyanide and if it still crashes with this version send the log

**Comment by JT122406** [comment]
Closing as no response was recieved
