### ISSUE TITLE
[1.20.1] Crash with Nature's Spirit in connector Environment

### ISSUE THREAD

**Issue by Reshy** [Potion-Studios/Oh-The-Biomes-Weve-Gone#18]
Crash: https://pastebin.com/4TEnZadZ
Log:  https://pastebin.com/CiawsJxm

![image](https://github.com/user-attachments/assets/ff3cfb5b-72d7-4b84-b071-7c4eb0befd30)
![image](https://github.com/user-attachments/assets/0cb8af5d-0cb9-42fa-84e2-3fdad6e34b47)

Plus naturespirit-1.6.0-1.20.1.jar from https://modrinth.com/mod/natures-spirit/version/1.6.0-1.20.1

Disablign Corgilib and BWG stops the crashing so it's an incompatibility

**Comment by JT122406** [comment]
Closing this in favor of #43
