### ISSUE TITLE
Storage Block Tags

### ISSUE THREAD

**Issue by TheBedrockMaster** [Potion-Studios/Oh-The-Biomes-Weve-Gone#183]
The following items should have the `c:storage_blocks` and `c:storage_blocks/{material}` item and block tags added:

Allium Petal Block: `c:storage_blocks/allium`
Pink Allium Petal Block: `c:storage_blocks/pink_allium`
White Allium Petal Block: `c:storage_blocks/white_allium`
Rose Petal Block: `c:storage_blocks/rose`

**Comment by JT122406** [comment]
I can add the tags, but 
Allium Petal Block: c:storage_blocks/allium
Pink Allium Petal Block: c:storage_blocks/pink_allium
White Allium Petal Block: c:storage_blocks/white_allium
Rose Petal Block: c:storage_blocks/rose

would all use the biomeswevegone namespace and not c since they aren't "common" tags they are ours, then all of them would be added to c:storage_blocks

**Comment by TheBedrockMaster** [comment]
Mods that add specific storage blocks, ingots, etc, still use the c namespace if they can be put as a / after the common tag, like `c:storage_blocks/allium`

**Comment by JT122406** [comment]
What other mods?

**Comment by TheBedrockMaster** [comment]
Just to name a few; Mekanism, AllTheOres, Allthemodium, PneumaticCraft, Ars Nouveau, Actually Additions, Advent of Ascension, The Undergarden, Twilight Forest, Croptopia and Applied Energistics 2. Most mods that can add them, do.

**Comment by JT122406** [comment]
I see what you are saying I looked at the undergarden, I'm gonna consult some other devs to see what the decision is here as it doesn't make sense to me to use the common id

**Comment by TheBedrockMaster** [comment]
If another mod adds a storage block for alliums, it's easier to unify them if they already have the same tag.

**Comment by JT122406** [comment]
That only makes sense in the case of MC blocks for blocks that we add it doesn't make sense

**Comment by TheBedrockMaster** [comment]
Any update on at least adding the allium block tag? Have you looked at examples in other mods?

**Comment by JT122406** [comment]
I moved them to c all of them
