### ISSUE TITLE
biomes continue even in caves

### ISSUE THREAD

**Issue by Kirinkare** [Potion-Studios/Oh-The-Biomes-Weve-Gone#19]
Some biomes lcontinue even to - 50, caves made of blocks from the surface biome
A lot of caves made from dirt

**Comment by Kirinkare** [comment]
![2024-07-29_01 23 30](https://github.com/user-attachments/assets/3aeff3d8-3366-48ac-b740-7db0a6437f36)

**Comment by JT122406** [comment]
If possible please list biomes

**Comment by Kirinkare** [comment]
from what I can see it happens in all biomes, including vanilla, maybe it's a bug with terrablender

**Comment by Kirinkare** [comment]
there are almost no cave biomes for the same reason

**Comment by JT122406** [comment]
The only biome I could see this happening with after the sakura grove one was patched yesterday would be BAOBAB_SAVANNA

**Comment by JT122406** [comment]
So if it's more than that and maybe allium shrubland it would be a terrablender issue

**Comment by Kirinkare** [comment]
i just found one under crag gardens, som maybe it is a terrablender issue

**Comment by JT122406** [comment]
Talked to Terrablender dev and this seems to be an issue that exists in Vanilla
