### ISSUE TITLE
Exception loading structure piece with id biomeswevegone:arch_piece

### ISSUE THREAD

**Issue by andriihorpenko** [Potion-Studios/Oh-The-Biomes-Weve-Gone#2]
## Description
Keep getting this exception every now and then. This results in chunk saving failure.
[latest.log](https://github.com/user-attachments/files/16404535/latest.log)
## Version
Latest beta build of BWG (published today)

**Comment by andriihorpenko** [comment]
Might be important to note: I had a world completely pre-generated on the latest alpha build of the mod. Today, I've upgraded to the first beta build.
This might be linked, however, I don't see any notice that alpha build worlds are incompatible with beta builds.

**Comment by JT122406** [comment]
> Might be important to note: I had a world completely pre-generated on the latest alpha build of the mod. Today, I've upgraded to the first beta build. This might be linked, however, I don't see any notice that alpha build worlds are incompatible with beta builds.

I think in the last alpha we might have not commented that code out when we should have so now that it’s out since we aren’t done with that biome that’s why this is popping up

**Comment by andriihorpenko** [comment]
Okay, good to know. If you're sure this the root cause - feel free to close the issue. Meanwhile, I'll rollback to the last working alpha build.

**Comment by JT122406** [comment]
@CorgiTaco can you confirm?

**Comment by JT122406** [comment]
@andriihorpenko I talked to corgi, so unfortunately this will not be fixed since we found a different way to do it so if you really wanna keep this world and update you'd need to delete the chunks with this structure in it.  This type of thing is unfortunate but was expected with breaking changes between alphas
