### ISSUE TITLE
orchard tree apples hover in midair after the leaves they were hanging on decay (but not if you manually break the block)

### ISSUE THREAD

**Issue by joebobthethird** [Potion-Studios/Oh-The-Biomes-Weve-Gone#25]
![2024-07-29_12 06 15](https://github.com/user-attachments/assets/622c2dc5-bfbb-49e8-8ef1-32f908dfce7b)

**Comment by JT122406** [comment]
Clearly this is a floating apple feature

**Comment by JT122406** [comment]
I'm kidding I will fix
