### ISSUE TITLE
igloos can generate in shattered glacier biomes and they look very out-of-place

### ISSUE THREAD

**Issue by joebobthethird** [Potion-Studios/Oh-The-Biomes-Weve-Gone#27]
![2024-07-29_16 52 46](https://github.com/user-attachments/assets/1b221a87-17ac-4632-9e19-727559ec8843)

**Comment by joebobthethird** [comment]
ngl a black snow igloo that generates in this biome would be sick

**Comment by JT122406** [comment]
> ngl a black snow igloo that generates in this biome would be sick

I agree, might decide to do this
