### ISSUE TITLE
Crash after adding BWG with dependencies

### ISSUE THREAD

**Issue by Hugo0272** [Potion-Studios/Oh-The-Biomes-Weve-Gone#3]
Crash report - https://mclo.gs/vOtn7Py

**Comment by JT122406** [comment]
> Crash report - https://mclo.gs/vOtn7Py

Not BWG
<html>
<body>

Mod File: /C:/Users/********/curseforge/minecraft/Instances/RPG Heroic Expeditions/mods/EpicFight-20.7.4.jar
--
81 | Failure message: Epic Fight (epicfight) has failed to load correctly

**Comment by dieeeeeeeego** [comment]
> Crash report - https://mclo.gs/vOtn7Py

thats alot of mods in that modpack. try removing mod by mod to see whats the incompatibile mod

**Comment by Hugo0272** [comment]
> > Crash report - https://mclo.gs/vOtn7Py
> 
> thats alot of mods in that modpack. try removing mod by mod to see whats the incompatibile mod

I already found it just by looking at what JT said, it was an epic fight addon
