### ISSUE TITLE
Incompatibility with Better Minecraft Modpack Series

### ISSUE THREAD

**Issue by lSherozl** [Potion-Studios/Oh-The-Biomes-Weve-Gone#30]
This was a solution I found and I am posting: Remove Aether Redux and disable these "biomes" in the config of BWG: {
  "araucaria_savanna": {
    "enabled": false
  },
  "sakura_grove": {
    "enabled": false
  }
}
The error java.lang.IllegalStateException: Feature order cycle found, involved sources suggests there is a cyclic dependency in the feature generation order involving the biomes minecraft:savanna, minecraft:windswept_savanna, biomeswevegone:araucaria_savanna, and biomeswevegone:sakura_grove. 
This is the simples solution I found in adding in the mod to your pack and making it work for Better minecraft modpacks. Posting the full logs will not be helpful, as there is too much, but the specific aspects and the crash report: 

org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/world/level/block/GrassBlock::placeGrass with priority 1000 cannot inject into net/minecraft/world/level/block/GrassBlock::m_214148_(Lnet/minecraft/server/level/ServerLevel;Lnet/minecraft/util/RandomSource;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/block/state/BlockState;)V merged by net.potionstudios.biomeswevegone.mixin.PrairieGrassMixin with priority 1000 [PREINJECT Applicator Phase -> aether_redux.mixins.json:common.block.GrassBlockMixin from mod aether_redux -> Prepare Injections ->  -> redirect$hhp001$aether_redux
[crash-2024-07-28_14.29.31-server.txt](https://github.com/user-attachments/files/16420849/crash-2024-07-28_14.29.31-server.txt)

And the crash report:

**Comment by JT122406** [comment]
This is something that will need to be delt with mod by mod or by the modpack developer

**Comment by lSherozl** [comment]
> This is something that will need to be delt with mod by mod or by the modpack developer

They said they wont be adding it due to its potential to break existing worlds, sooooo I am going to figure this out myself

**Comment by lSherozl** [comment]
> This is something that will need to be delt with mod by mod or by the modpack developer

HOWEVER, the cylic chunk issue is present in a lot of modpacks, and many people are getting that crash report, please look into a least that

**Comment by lSherozl** [comment]
> This is something that will need to be delt with mod by mod or by the modpack developer

Solved.....I found the issue but its more complex, update Farmers Delight and Delightful in the modpack, that way you can use Aether Redux, however, there are still issues with textures and what not, and the main culprit is Delightful, remove it entirely and there are no more issues....Delightful causes a conflict with [01Aug2024 03:19:48.645] [Thread-194/ERROR] [EMI/]: [EMI] java.lang.NoSuchMethodError: 'byte net.zepalesque.redux.item.util.VeridiumItem.getInfusion(net.minecraft.world.item.ItemStack)'
	at TRANSFORMER
[01Aug2024 03:19:48.645] [Thread-194/ERROR] [EMI/]: [EMI] delightful@3.5.5
[01Aug2024 03:19:48.645] [Thread-194/ERROR] [EMI/]: [EMI] net.brnbrd.delightful.common.item.knife.compat.aether_redux.VeridiumKnifeItem.m_7373_(VeridiumKnifeItem.java:51)
	at TRANSFORMER
[01Aug2024 03:19:48.645] [Thread-194/ERROR] [EMI/]: [EMI] minecraft@1.20.1
[01Aug2024 03:19:48.645] [Thread-194/ERROR] [EMI/]: [EMI] net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:631)
	at TRANSFORMER
[01Aug2024 03:19:48.645] [Thread-194/ERROR] [EMI/]: [EMI] emi@1.1.2+1.20.1+forge
[01Aug2024 03:19:48.645] [Thread-194/ERROR] [EMI/]: [EMI] dev.emi.emi.api.stack.ItemEmiStack.getTooltipText(ItemEmiStack.java:140)
	at TRANSFORMER
[01Aug2024 03:19:48.645] [Thread-194/ERROR] [EMI/]: [EMI] emi@1.1.2+1.20.1+forge
[01Aug2024 03:19:48.645] [Thread-194/ERROR] [EMI/]: [EMI] dev.emi.emi.search.EmiSearch.bake(EmiSearch.java:59)
	at TRANSFORMER
[01Aug2024 03:19:48.645] [Thread-194/ERROR] [EMI/]: [EMI] emi@1.1.2+1.20.1+forge
[01Aug2024 03:19:48.645] [Thread-194/ERROR] [EMI/]: [EMI] dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:220)
	at java.base
[01Aug2024 03:19:48.645] [Thread-194/ERROR] [EMI/]: [EMI] java.lang.Thread.run(Thread.java:833)

**Comment by lSherozl** [comment]
Due to the EMI issue which is the search bar thing in creative.....I am seeing conflicts between Aether Redux, Delightful, Farmers Delight and EMI..............Updating above said mods fixes it and loads the world, but this will need to be reported to the devs of said mods and I am too tired to do it now

**Comment by brnbrd** [comment]
This is using an outdated version of Delightful (3.5.5). The incompatibility with Aether Redux is fixed already.
