### ISSUE TITLE
[1.20.1] Crash with Wythers:  Feature Orcer Cycle

### ISSUE THREAD

**Issue by Reshy** [Potion-Studios/Oh-The-Biomes-Weve-Gone#35]
Crash:  https://pastebin.com/S0qwPz0N
Log:  https://pastebin.com/AuA5miST

![image](https://github.com/user-attachments/assets/592433af-0930-4231-800c-68d1d86b5147)
![image](https://github.com/user-attachments/assets/acc31b0e-1911-471a-b33b-3558578a35b8)

**Comment by JT122406** [comment]
See #16
