### ISSUE TITLE
apple trees doenst drop apple

### ISSUE THREAD

**Issue by SCAFprivate** [Potion-Studios/Oh-The-Biomes-Weve-Gone#36]
referring to the topic, the apple trees (fruit trees?) from that specific biome doesnt drop apple, while they used to drop apple in byg

**Comment by JT122406** [comment]
Which Apple Trees? the Green ones or Red ones or what biomes

**Comment by SCAFprivate** [comment]
it is the orchard tree, and the biome is just called orchard, sorry didnt use english so not knowing the name. None of the leaves with texture of white flower, red apples or no extra texture drop apples, though there are quite few apple blocks attached to leaves, but they also not automatically broken when the leaves are decayed.

**Comment by JT122406** [comment]
the broken on decay I just patched

**Comment by SCAFprivate** [comment]
should the leaves still drop apples when decay? I'm uncertain if this is a bug or feature from byg that is removed

**Comment by JT122406** [comment]
Can you try with 1.0.2-Beta and lmk

**Comment by SCAFprivate** [comment]
still only saplings drop from leaves, didnt find any apple drop from leaves.

**Comment by JT122406** [comment]
wait do you mean like when breaking the leaves?

**Comment by JT122406** [comment]
Ah I didn't realize they did that but just looked back at the old code and it does

**Comment by SCAFprivate** [comment]
yes, i mean apple drops when break leaves
