### ISSUE TITLE
Incompatibility with Cliff under a Tree

### ISSUE THREAD

**Issue by Lenatus** [Potion-Studios/Oh-The-Biomes-Weve-Gone#37]
If world generation is performed with both mods installed, a crash will occur. Also, if a world generated only with BWG is started with the CliffTree mod installed, it crashes when TPing to the CliffTree biome.

**Environment**
- Forge 47.5.3
- Oh The Biomes We've Gone 1.0.1-Beta
- Oh The Trees You'll Grow 1.2.0
- GeckoLib4 4.4.7
- CorgiLib 4.0.2.0
- Cliff under a Tree 1.1

**Comment by CorgiTaco** [comment]
Please send a crash log @Lenatus

**Comment by JT122406** [comment]
I have fixed this in 9c31a320dfcd28d7feec955e61d8449ea85c12af
