### ISSUE TITLE
Floating Man O War

### ISSUE THREAD

**Issue by Uniter343** [Potion-Studios/Oh-The-Biomes-Weve-Gone#38]
When Man O War swim at the surface they can be entirely out of the water for extended periods of time, Not sure if anything can be done about this.

![2024-07-30_16 46 14](https://github.com/user-attachments/assets/b81b62f4-6afc-4e70-9c6c-f8139ba1df1b)

**Comment by JT122406** [comment]
Small texture and model issue and will not be fixed
