### ISSUE TITLE
Biome Features being hallucinated at wrong y-level by Distant Horizons

### ISSUE THREAD

**Issue by Uniter343** [Potion-Studios/Oh-The-Biomes-Weve-Gone#39]
Not sure if this is in any way at all your fault, just thought I would post it here too so you guys are aware of it.

https://github.com/user-attachments/assets/80bd6249-fb40-49c7-a1e9-f8cf902825f3

![Screenshot 2024-07-30 165848](https://github.com/user-attachments/assets/502e978a-8976-40c1-ab3d-d09acc7ff31f)

To be clear this only happens when DIstant horizons inbuilt generator is used, so it is probably their fault (?).

**Comment by JT122406** [comment]
Why are you reporting it to us then

**Comment by Uniter343** [comment]
I figured it may be caused by the way you do these features/terrain, since I haven't seen this issue with other mods features.

**Comment by JT122406** [comment]
maybe, @CorgiTaco Could you take a look at this?

**Comment by JT122406** [comment]
Going to close this as from what the team can tell it's on the Distant Horizons side
