### ISSUE TITLE
Crash while loading world (Temp Solution: Use Feature Recycler)

### ISSUE THREAD

**Issue by Kailgroz** [Potion-Studios/Oh-The-Biomes-Weve-Gone#41]
While I'm loading the world the load doesn't go up from 0% and then crashes
[crash-2024-07-30_13.42.31-server.txt](https://github.com/user-attachments/files/16431668/crash-2024-07-30_13.42.31-server.txt)

**Comment by Kailgroz** [comment]
[latest.log](https://github.com/user-attachments/files/16431670/latest.log)

**Comment by JT122406** [comment]
Using other worldgen mods?

**Comment by CorgiTaco** [comment]
Temporary solution is to use: https://www.curseforge.com/minecraft/mc-mods/feature-recycler
