### ISSUE TITLE
Incompatible with Abnormals Mods (Temp Solution: Use Feature Recycler)

### ISSUE THREAD

**Issue by PercyJames** [Potion-Studios/Oh-The-Biomes-Weve-Gone#51]
https://pastebin.com/QrXPsh61

**Comment by CorgiTaco** [comment]
Temporary solution is to use: https://www.curseforge.com/minecraft/mc-mods/feature-recycler

**Comment by Apollounknowndev** [comment]
Duplicate of #6, it's actually Excessive Building causing the error looking in the crash report.

**Comment by JT122406** [comment]
Follow on #6
