### ISSUE TITLE
Jacaranda planks cannot be used to craft chests and also all crafting tables from BWG cannot be used as an ingrediant for recipes that need a crafting table

### ISSUE THREAD

**Issue by PopSikle23** [Potion-Studios/Oh-The-Biomes-Weve-Gone#52]
![image](https://github.com/user-attachments/assets/8a5644e1-3c40-4461-9a04-1ed996227552)
![image](https://github.com/user-attachments/assets/9cd3a27c-8dfc-46b1-9bfe-15c05b22c5cd)

**Comment by JT122406** [comment]
What recipes use a crafting table?

**Comment by JT122406** [comment]
Since if it's from another mod we cannot do anything about that they would need to adjust there recipes, if it's vanilla that's another story

**Comment by PopSikle23** [comment]
ah alr ill just wait for the other mod devs

**Comment by JT122406** [comment]
Also you must have sometype of conflict because 
![image](https://github.com/user-attachments/assets/c13ed57d-755b-4cc3-bc51-4da829ace9d4)
for me it works

**Comment by PopSikle23** [comment]
i have no idea what mod could conflict with this one

**Comment by natkos21** [comment]
If you have Quark installed, "Variant Chests" make it impossible to craft chests with BWG wood
