### ISSUE TITLE
crash in my modpack bellow is the log (Temp Solution: Use Feature Recycler)

### ISSUE THREAD

**Issue by Thunderrock424242** [Potion-Studios/Oh-The-Biomes-Weve-Gone#53]
was loading up creating a new world stuck on 0% then crashed 
[latest.log](https://github.com/user-attachments/files/16464631/latest.log)

**Comment by Thunderrock424242** [comment]
btw you can find the modlist in the log

**Comment by CorgiTaco** [comment]
Temporary solution is to use: https://www.curseforge.com/minecraft/mc-mods/feature-recycler

**Comment by Apollounknowndev** [comment]
Duplicate of #16, conflict with WWEE.

**Comment by JT122406** [comment]
Follow on #16
