### ISSUE TITLE
various crashes (Temp Solution: Use Feature Recycler)

### ISSUE THREAD

**Issue by pibblepower** [Potion-Studios/Oh-The-Biomes-Weve-Gone#54]
so, i'm playing on a modified version of ATM 9. When using this mod alongside some of the others I've added, the game crashes when I try to load a world. It seems to be a problem with maybe the abnormal's mods, world of wonder, or both. Here's the crash reports:
[crash-2024-07-31_17.39.42-server.txt](https://github.com/user-attachments/files/16464927/crash-2024-07-31_17.39.42-server.txt)
[crash-2024-07-31_19.25.53-server.txt](https://github.com/user-attachments/files/16464928/crash-2024-07-31_19.25.53-server.txt)
[crash-2024-08-01_21.49.56-server.txt](https://github.com/user-attachments/files/16464929/crash-2024-08-01_21.49.56-server.txt)
[crash-2024-08-01_22.14.08-server.txt](https://github.com/user-attachments/files/16464930/crash-2024-08-01_22.14.08-server.txt)

**Comment by CorgiTaco** [comment]
Temporary solution is to use: https://www.curseforge.com/minecraft/mc-mods/feature-recycler

**Comment by JT122406** [comment]
Please try with 1.3.0 or 2.1.0 As this had compatibility changes that might close this.
Waiting 3 days for response before closing
