### ISSUE TITLE
leaves crash

### ISSUE THREAD

**Issue by birmss** [Potion-Studios/Oh-The-Biomes-Weve-Gone#56]
When trees are destroyed，After the leaves begin to rot my game will crash
[Uploading crash-2024-08-03_09.21.53-server.txt…]()

**Comment by birmss** [comment]
only trees in this mod

**Comment by JT122406** [comment]
![image](https://github.com/user-attachments/assets/fa082ab9-7294-45ea-9e0d-5097de16cd4d)
File never uploaded

**Comment by birmss** [comment]
[latest[1].log](https://github.com/user-attachments/files/16477806/latest.1.log)

**Comment by birmss** [comment]
[latest[1].log](https://github.com/user-attachments/files/16477826/latest.1.log)

**Comment by birmss** [comment]
Crashed only when the leaves of the fruit tree rot

**Comment by Eletoast** [comment]
Was experiencing the same crash on a personal modpack, but was unsure if it was an issue with Sinytra or not.

**Comment by birmss** [comment]
> Was experiencing the same crash on a personal modpack, but was unsure if it was an issue with Sinytra or not.

Maybe not, i dont use Sinytra

**Comment by LordofDorknes** [comment]
[crash-2024-08-03_01.46.44-server.txt](https://github.com/user-attachments/files/16478790/crash-2024-08-03_01.46.44-server.txt)
Hopefully this crash log uploads.

**Comment by JT122406** [comment]
Is it only Fruit Trees?

**Comment by Eletoast** [comment]
Seems so. Standing idle in an Orchard biome will eventually crash the game (well, server).

**Comment by JT122406** [comment]
Can someone try with just bwg and our depos and see if it happens?

**Comment by JT122406** [comment]
It has something to do with the way leaves drop resources, I use a copy of the vanilla code for the fruit leaves decay so I wonder if something is messing with it

**Comment by Eletoast** [comment]
It seems to not crash with just BWG and it's dependencies. When I experienced the crash, it blamed any forge port of lithium I tried to use (radium or canary).

**Comment by genesy** [comment]
[crash-2024-08-03_13.43.50-server.txt](https://github.com/user-attachments/files/16480811/crash-2024-08-03_13.43.50-server.txt)
Also getting this issue when I spawn in the world.

**Comment by Eletoast** [comment]
Seems to be an incompat with lithium forks.

**Comment by dadadadaan** [comment]
Only happens on versions 1.0.3+. If I had to guess, probably has something to do with the fruit leaves drop fix for issue #36 .

**Comment by birmss** [comment]
It also incompatible with Fast Leaf Decay

**Comment by LordofDorknes** [comment]
@JT122406 @Eletoast 
I can confirm it is _not_ an incompatibility. I can straightforwardly reproduce the crash with only the requirements of Biomes We've Gone by planting an orchard sapling, bonemealing it, and removing enough wood that the leaves start to decay.
[crash-2024-08-03_14.12.42-server.txt](https://github.com/user-attachments/files/16482919/crash-2024-08-03_14.12.42-server.txt)

**Comment by dadadadaan** [comment]
> It also incompatible with Fast Leaf Decay

I think that fast leaf decay just makes the crash, well, faster. I tried without fast leaf decay running and had the same issue.

**Comment by LordofDorknes** [comment]
It occurs with any trees (Skyris, orchard, yucca, baobob) with loot tables added in the commit c646cd4d260c7a569773217ecd177f1a6eb2061e and possibly other commits if tree loot tables were updated elsewhere.

**Comment by Happy1speed** [comment]
Yes, this seems to be happening for me too

`at net.potionstudios.biomeswevegone.world.level.block.plants.tree.leaves.BWGFruitLeavesBlock.method_9514(BWGFruitLeavesBlock.java:30)`

**Comment by JT122406** [comment]
So is this now happening without Litium/Lithium forks?
And or fast leave decay

**Comment by JT122406** [comment]
This is all a bit odd since it references the error in my code for dropping resources on decay, however it doesn't like the loottable but I use the same loottable as the oak leaves with apples for our fruit leaves

**Comment by birmss** [comment]
> 那么，现在没有 Litium/Lithium 分叉，这种情况会发生吗？和/或快速离开腐烂

yes

**Comment by LordofDorknes** [comment]
Could it be that only some variants (base, flowering, fruiting) of the leaf blocks are getting their loottable registered (so some say their loottable has length zero) but all variants are trying to trigger a drop upon decay?

**Comment by LordofDorknes** [comment]
For skyris trees at least, I can trigger the crash consistently when a fruiting leaf block tries to decay. I can't trigger it for the base or flowering blocks, so it does seem to have something to do with the added loot tables for fruiting leaves specifically.

**Comment by JT122406** [comment]
> Could it be that only some variants (base, flowering, fruiting) of the leaf blocks are getting their loottable registered (so some say their loottable has length zero) but all variants are trying to trigger a drop upon decay?

Loottables are done in json so there is no like register

**Comment by JT122406** [comment]
> For skyris trees at least, I can trigger the crash consistently when a fruiting leaf block tries to decay. I can't trigger it for the base or flowering blocks, so it does seem to have something to do with the added loot tables for fruiting leaves specifically.

with just bwg?

**Comment by LordofDorknes** [comment]
@JT122406 Yes, only BWG and its dependencies.

**Comment by JT122406** [comment]
So the drops on this jar are not correct it'll be just normal apples for all fruit leaves but someone please test and if you crash send the log here if not then also let us know: 
https://discord.com/channels/636017992265891846/636020573046308874/1269523101385887827

**Comment by LordofDorknes** [comment]
> So the drops on this jar are not correct it'll be just normal apples for all fruit leaves but someone please test and if you crash send the log here if not then also let us know: https://discord.com/channels/636017992265891846/636020573046308874/1269523101385887827
@JT122406 
Identical crashing behavior on the Forge snapshot jar.

[crash-2024-08-03_22.40.01-server.txt](https://github.com/user-attachments/files/16486427/crash-2024-08-03_22.40.01-server.txt)

**Comment by JT122406** [comment]
@LordofDorknes Can you send me the log, I put debugs in it

**Comment by futill** [comment]
[crash-2024-08-04_21.38.34-server.txt](https://github.com/user-attachments/files/16487843/crash-2024-08-04_21.38.34-server.txt)

**Comment by JT122406** [comment]
Alright I'm gonna lose my mind, I changed the drops back to using normal mc leaf drops and It's still crashing

**Comment by JT122406** [comment]
I have now tried using only the method from the vanilla Leavesblock and using the default leaves portable maker and I’m still crashing

**Comment by dadadadaan** [comment]
Flowering Skyris leaves are still causing the same crashes for me. I tested all the following though as well and seem fine so far:

Baobab ✅
Orchard ✅
Palo Verde ✅
Jacaranda ✅
Indigo Jacaranda ✅
Yucca ✅

Not sure if there are any other leaves considered fruit or flowering that I didn't test, but I figured I'd go through a bunch of them to see if any other than Skyris slipped through.

**Comment by JT122406** [comment]
Just the ripe ones are fruit, flowering didn't have the issue before

**Comment by genesy** [comment]
[crash-2024-08-05_15.18.08-server.txt](https://github.com/user-attachments/files/16492327/crash-2024-08-05_15.18.08-server.txt)
This happened on the latest version 1.0.5 beta

**Comment by Happy1speed** [comment]
Still active unfortunately

**Comment by pokesmells** [comment]
Can confirm, also receiving such a crash on 1.0.5 Beta. Will attach a log for further review.

This occurs on a 1.20.1 Fabric instance.

https://mclo.gs/acPBPFG

**Comment by celestmia** [comment]
Seems like issue is the fortune chances (for dropping saplings) doesn't have at least one entry (which is used when there is no fortune). I took a look at the other fruit leaves before the workaround and they had a similar issue with their sapling drops.

Current crashing entry (in `data/biomeswevegone/loot_tables/blocks/green_apple_skyris_leaves.json`):
```
{
  "type": "minecraft:item",
  "conditions": [
    {
      "condition": "minecraft:survives_explosion"
    },
    {
      "chances": [],
      "condition": "minecraft:table_bonus",
      "enchantment": "minecraft:fortune"
    }
  ],
  "name": "biomeswevegone:skyris_sapling"
}
```

Fixed entry (matched changes with oak saplings loot table):
```
{
  "type": "minecraft:item",
  "conditions": [
    {
      "condition": "minecraft:survives_explosion"
    },
    {
      "chances": [
        0.05,
        0.0625,
        0.083333336,
        0.1
      ],
      "condition": "minecraft:table_bonus",
      "enchantment": "minecraft:fortune"
    }
  ],
  "name": "biomeswevegone:skyris_sapling"
}
```

**Comment by JT122406** [comment]
That is a good point I didn’t think about it, I will fix that
