### ISSUE TITLE
Incompatibility with Excessive Building (Temp Solution: Use Feature Recycler)

### ISSUE THREAD

**Issue by Devilswarchild** [Potion-Studios/Oh-The-Biomes-Weve-Gone#6]
Booting to menu works just fine but the second I try to load a world or start a fresh one, Im greeted with nothing but black, can't see, can't move nothing.

[debug.log](https://mclo.gs/tOmTzZu)

[latest.log](https://mclo.gs/qJ5INH4)

[MineColonies: Dimensional Adventure Modpack](https://www.curseforge.com/minecraft/modpacks/minecolonies-dimensional-adventure)

![Screenshot_3](https://github.com/user-attachments/assets/ed2155b6-fee5-4299-9270-7564992eba29)

MC Version: 1.20.1
Forge Version 47.3.5
BWG Version: 1.0.0-Beta-SNAPSHOT

**Comment by ambientNexus** [comment]
ignore the closed on that issue, dev improperly marked it as complete instead of won't fix

**Comment by CorgiTaco** [comment]
Temporary solution is to use: https://www.curseforge.com/minecraft/mc-mods/feature-recycler
