### ISSUE TITLE
Game crashes when placing Enchanted Tree Saplings in v1.0.5Beta for Forge 47.3.0

### ISSUE THREAD

**Issue by ZerxusB74** [Potion-Studios/Oh-The-Biomes-Weve-Gone#63]
This issue doesn't affect any other saplings, only the blue and green enchanted saplings. As soon as placed down, the game freezes, shows a "saving world" screen, and then crashes right away, with "exit code - 1". 
[Full_modpack_crashlog.txt](https://github.com/user-attachments/files/16500361/Full_modpack_crashlog.txt)
[Crashlog_during_just_BWG.txt](https://github.com/user-attachments/files/16500362/Crashlog_during_just_BWG.txt)

Kindly look into it, bcoz you guys have marked it as fixed earlier, but that seems like it was only for fabric.

**Comment by JT122406** [comment]
It has been fixed just hasn’t been pushed to a release yet

**Comment by ZerxusB74** [comment]
> It has been fixed just hasn’t been pushed to a release yet

I see, thanks for informing. Waiting for the next release 😄
