### ISSUE TITLE
Cypress Sapling

### ISSUE THREAD

**Issue by Dumpling00** [Potion-Studios/Oh-The-Biomes-Weve-Gone#66]
Hello! Had a question about Cypress Saplings, as they don't seem to grow with bone meal. Do they need to be planted on a particular block? Or is this a bug?

I'm on Fabric 1.20.1

**Comment by JT122406** [comment]
I’ll check it, it might just be bugged saplings got done last so some stuff got misses

**Comment by JT122406** [comment]
Baobab uses 2 by 2

> Thanks! Same thing seems to happen with the baobab sapling. I'm testing the others, I'll add more posts if I find anything else!

**Comment by Dumpling00** [comment]
> Baobab uses 2 by 2
> 
> > Thanks! Same thing seems to happen with the baobab sapling. I'm testing the others, I'll add more posts if I find anything else!

I always test saplings on open areas - I'm currently testing these on a flatworld, so I don't think space is the issue!

Worth noting however, I also have Regions Unexplored, WilderWilds and Let'sDo Blooming Nature. Reason I say this is that all of them add their own Cypress trees, while Regions Unexplored and BloomingNature have their own Baobab.

There are also other "copies" such as Fir, Ebony and Palm but those are all working. Regions Unexplored's Baobab also doesn't seem to grow, so I'll be reporting that to them as well. :)

**Comment by JT122406** [comment]
So I tested and got Baobab and Cypress to grow, Baobab uses 2 by 2 and for the next update Cypress will also use 2 by 2 due to how large the trees it makes are.

**Comment by Dumpling00** [comment]
I see, so this might be a conflict with the other mods, maybe?

**Comment by JT122406** [comment]
It might be, what type of block are you planting on and if possible take a video

**Comment by Dumpling00** [comment]
Nevermind I've managed to make the baobab grow! Cypress still isn't having any of it though

**Comment by Dumpling00** [comment]
Okay so - it seems like I needed pretty much a whole chunk of free space for this one. Cypress has grown haha.
Sorry to waste your time.

**Comment by JT122406** [comment]
You are all good
