### ISSUE TITLE
[1.20.1] Enchanted Trees have no Glow

### ISSUE THREAD

**Issue by AmythystHeart** [Potion-Studios/Oh-The-Biomes-Weve-Gone#7]
Bug is as titled. The glow for the enchanted trees hasn't been turned back on. If the witch Hazel is supposed to glow at the same luminosity as the old enchanted trees, that glow is also turned off. 

![2024-07-28_19 26 16](https://github.com/user-attachments/assets/05df6f9d-ab15-4ebc-a6cd-a809061acc31)
![2024-07-28_18 52 45](https://github.com/user-attachments/assets/c2ec4142-a02b-4121-8c0d-6c96df94778a)

**Comment by AmythystHeart** [comment]
Forgot to add: The luminosity does show up on the Xaero's map/minimap, so that's all good.

**Comment by JT122406** [comment]
They glow for me? what loader?

**Comment by AmythystHeart** [comment]
Forge

**Comment by JT122406** [comment]
![image](https://github.com/user-attachments/assets/8356bdbf-8111-44ef-aa2d-086223747dbc)
They have glow light level is just low
