### ISSUE TITLE
Swamp biomes can't be disabled

### ISSUE THREAD

**Issue by CarLos4475** [Potion-Studios/Oh-The-Biomes-Weve-Gone#71]
I tested with only the mod and its dependences in a new profile and the bug is from the mod, I disabled the bayou and the white mangrove in the config and nothing happens, the biomes are still generating. the other biomes work fine. I know that I've been very upset with this but is important to modpacks. 
![Captura de pantalla 2024-08-08 180148](https://github.com/user-attachments/assets/515eeaba-7f95-4d67-98ac-2e8f6a9aee5b)

![Imagen de WhatsApp 2024-08-08 a las 18 02 34_53eb5e5d](https://github.com/user-attachments/assets/9d7054da-f1be-4aea-90dd-9c6f6bb290f7)

**Comment by JT122406** [comment]
@CorgiTaco If possible take a look at this when you have a moment

**Comment by CorgiTaco** [comment]
Patched in https://github.com/Potion-Studios/Oh-The-Biomes-Weve-Gone/commit/d5cbde6bf9567769027b11825808548b418a46a3
