### ISSUE TITLE
Cattail Unharvestable

### ISSUE THREAD

**Issue by Rayxanber** [Potion-Studios/Oh-The-Biomes-Weve-Gone#77]
Cattail Sprouts can be harvested but the adult plant cannot. Fabric Version 1.0.6

**Comment by JT122406** [comment]
Like it has no drops?

**Comment by Rayxanber** [comment]
Yes, using Shears, Silk Touch, hoe or bare hand nothing drops from grown cattails. The sprouts will drop themselves properly.
