### ISSUE TITLE
bwg  is somehow, causing the biome "terrablender:deferred_placeholder" to spawn everywere

### ISSUE THREAD

**Issue by Thinkseal** [Potion-Studios/Oh-The-Biomes-Weve-Gone#79]
so at first I thought this was not a bug with bwg basses on how I had changed many other mods some of which are in a much more buggy state but it turns out that it was actually bwg.
in a modpack I have made on modrinth [yam](https://modrinth.com/modpack/yam) when it has bwg which it already does it will generate terrablender:deferred_placeholder over about 50% of the world but when you remove it it does not generate at all.
I also tested just bwg with all of its dependencies on quilt (modloader the modpack uses) and it did not have that problem so I believe that this is a conflict with another mod if you want me to test, what that is, I can but I currently have not done that yet.
In addition to this, I think a lot of people have been having this issue in the discord based on searching deferred_placeholder in the chat.

**Comment by CorgiTaco** [comment]
Duplicate of #15
