### ISSUE TITLE
Terralith biomes not generating with the correct blocks when using BWG and Feature Recycler

### ISSUE THREAD

**Issue by KB-Q** [Potion-Studios/Oh-The-Biomes-Weve-Gone#81]
Basically what it says in the title. 
Attached screenshot for reference: you can see terralith:volcanic_peaks is not generating with the correct basalt and lava blocks

MC version: 1.20.1 Fabric

Modslist: https://pastebin.com/sNSp6qsH

![2024-08-11_20 28 44](https://github.com/user-attachments/assets/fe973aca-b958-422a-a2fe-ea0cac5dcd12)

**Comment by JT122406** [comment]
@CorgiTaco This is all you

**Comment by JT122406** [comment]
Actually

**Comment by JT122406** [comment]
Does it work when not using feature recycler ?

**Comment by CorgiTaco** [comment]
This does not touch surface rules in any sort of way

**Comment by Apollounknowndev** [comment]
Likely an issue with using Tectonic with the Increased Height setting on.

https://github.com/Apollounknowndev/tectonic/issues/177
