### ISSUE TITLE
Black Ice Xray when using Sodium

### ISSUE THREAD

**Issue by xamionex** [Potion-Studios/Oh-The-Biomes-Weve-Gone#83]
With Sodium:
![image](https://github.com/user-attachments/assets/3ec8bed3-8de1-4bf1-9313-4033eadb4401)
Without sodium:
![image](https://github.com/user-attachments/assets/8643f0a2-9224-40c6-b450-e7ad1e28704b)

Clarify if this is user error or something I'm missing as the only mods that are loaded are OTBWG (+ Dependencies) and Sodium
(Also to clarify, this does not happen with normal ice, just black ice from OTBWG)

**Comment by CorgiTaco** [comment]
This seems more like an issue with sodium than bwg but will leave this open if someone provides input.

**Comment by xamionex** [comment]
> This seems more like an issue with sodium than bwg but will leave this open if someone provides input.

I looked into it and supposedly it's been fixed but I'm gonna look around more, could be that it's a newer version of sodium and I'm on 1.20.1 and can't use it

**Comment by xamionex** [comment]
Workaround by using [Embeddium](https://modrinth.com/mod/embeddium)
