### ISSUE TITLE
Swamp biomes are disabled no matter setting in config

### ISSUE THREAD

**Issue by Rayxanber** [Potion-Studios/Oh-The-Biomes-Weve-Gone#86]
The 3 Swamp biomes mentioned in this issue here:  https://github.com/Potion-Studios/Oh-The-Biomes-Weve-Gone/issues/71 no longer exist if they were not previously generated, and are unable to be found using the /locate biome command. Biomes are set to true for spawning in config. Tested in an instance with no other mods (except BWG dependencies) installed.

**Comment by JT122406** [comment]
fixed in e8c7e543190ac5e3bd114f4474d67cc995554663
