### ISSUE TITLE
Added forge:stripped_logs tag to stripped logs for Create mod compatibility.

### ISSUE THREAD

**Issue by Junnaturefox** [Potion-Studios/Oh-The-Biomes-Weve-Gone#87]
This will allow logs from BWG can be used to make Create casing blocks
It would be nice to also add a forge:stripped_wood tag for stripped wood :)
![QQ20240815-203139](https://github.com/user-attachments/assets/3e737219-8104-4a9e-822c-f04a0a4d6d4b)

**Comment by JT122406** [comment]
There is no forge stripped logs tag

**Comment by iBryguy** [comment]
> There is no forge stripped logs tag

It's... complicated. The default forge tags, in my experience, are rather limited. But forge allows mods to [introduce their own forge tags by using the the forge namespace. ](https://docs.minecraftforge.net/en/1.20.x/resources/server/tags/#conventions)

There's no default `#forge:stripped_logs`, but the Create mod does add the item tag `#forge:stripped_logs` (as well as `#forge:stripped_wood` , though I'm not yet sure what that's used for)

**Comment by JT122406** [comment]
> > There is no forge stripped logs tag
> 
> It's... complicated. The default forge tags, in my experience, are rather limited. But forge allows mods to [introduce their own forge tags by using the the forge namespace. ](https://docs.minecraftforge.net/en/1.20.x/resources/server/tags/#conventions)
> 
> There's no default `#forge:stripped_logs`, but the Create mod does add the item tag `#forge:stripped_logs` (as well as `#forge:stripped_wood` , though I'm not yet sure what that's used for)

If we start adding random tags it'll be expected we do this for all mods, you can make a pr for it but honestly in this case Since it's a tag made for another mod it would make more sense to just add our blocks as optionals to there tag or I can create a tag for it under the bwg namespace and then they can add that tag as an optional
