### ISSUE TITLE
Tag issues in 1.20.1

### ISSUE THREAD

**Issue by TelepathicGrunt** [Potion-Studios/Oh-The-Biomes-Weve-Gone#88]
Copied pasted from discord:

- in biomeswevegone, the item form of the flower patch is very green
- why are several flowers not tagged as flowers? like many flowers that have visual flowers on them are not tagged in block form 
- why is horseweed and winter succulent tagged a flower?
- just to be clear about flowers:
`minecraft:small_flowers` for small single block normal flowers like vanilla's dandelions or tulips
`minecraft:tall_flowers` for 2 block high flowers like rose bush
`minecraft:flowers` for any special flowers that doesnt fit in others like your cactus flower or petals or flowering lily or witch hazel blossom 

Side note, I dont think biomeswevegone:eroded_borealis actually spawns. Teleported a ton of times and did search command

**Comment by JT122406** [comment]
Very Green Flower patch fixed in: 84fca3fb2b1b5e8103803ec861a46c315ab3eaed
