### ISSUE TITLE
Mahogany trees in fragment jungle biome sometimes go down to and through bedrock

### ISSUE THREAD

**Issue by joebobthethird** [Potion-Studios/Oh-The-Biomes-Weve-Gone#89]
![2024-08-16_19 30 10](https://github.com/user-attachments/assets/cdd3d62c-c9b7-4f64-a50f-5a572d54a347)
![2024-08-16_19 32 42](https://github.com/user-attachments/assets/3e902733-be1d-4ba3-89d5-30b63e03c5fd)
I know trees have roots but this is a bit ridiculous

**Comment by joebobthethird** [comment]
it seems to also happen with oak trees in the fragment jungle

**Comment by JT122406** [comment]
Yeah it seems to be a issue with TYG and the chance that the tree doesn’t see a block it can grow to

**Comment by JT122406** [comment]
So the going through bedrock I just addressed in this commit on TYG:
https://github.com/CorgiTaco/Oh-The-Trees-Youll-Grow/commit/4e00b60317a01e1ded48786289eaee6263407ab3

**Comment by JT122406** [comment]
The going under the surface Is a whole other issue
