### ISSUE TITLE
game crashes while loading world

### ISSUE THREAD

**Issue by Nightfigure** [Potion-Studios/Oh-The-Biomes-Weve-Gone#9]
this is likely due to a mod incompatability, i'll post the log below 
[latest.log](https://github.com/user-attachments/files/16405810/latest.log)

**Comment by JT122406** [comment]
What other worldgen mod do you have?

**Comment by Nightfigure** [comment]
currently i have:
twigs
biomes so plenty
regions unexplored
alexs caves
mystics biomes
and quark

**Comment by lSherozl** [comment]
Can confirm it crashes with alex caves

**Comment by Eletoast** [comment]
Whats your mod list? I have a pack with 250+ mods and BWG runs just fine and have experience no crashes.

**Comment by Nightfigure** [comment]
> Can confirm it crashes with alex caves

deleted alexs caves from the modlist and loaded the world, still crashed

**Comment by Eletoast** [comment]
Are you able to send a crash log? It could help narrow down what mod could be causing the crash.

**Comment by Nightfigure** [comment]
> Are you able to send a crash log? It could help narrow down what mod could be causing the crash.

yea, sorry for the late reply btw
[crash-2024-07-28_20.05.33-client.txt](https://github.com/user-attachments/files/16416436/crash-2024-07-28_20.05.33-client.txt)

**Comment by Eletoast** [comment]
Seems like an issue with the mod legendiumcurrency. Try uninstalling that and creating a new world.

**Comment by Nightfigure** [comment]
ok yes, it does work now. thanks for the help
