### ISSUE TITLE
bamboo generates on top of mahogany tree base (or maybe the mahogany tree generates through bamboo)

### ISSUE THREAD

**Issue by joebobthethird** [Potion-Studios/Oh-The-Biomes-Weve-Gone#92]
![2024-08-22_21 13 39](https://github.com/user-attachments/assets/5d1f78bd-8c7e-4d41-9331-507f9324b5f1)

**Comment by JT122406** [comment]
Is this at the edge between 2 biomes?

**Comment by joebobthethird** [comment]
nope, its the same biome

**Comment by JT122406** [comment]
So Going into this more it's not something we can control since Vanilla should be checking to make sure that the block below is either bamboo or a bamboo growable.  Looking from the other side with the tree removing it that would be on the TYG side but It's more on the vanilla side
