### ISSUE TITLE
I get that the dead sea biome would be hard to navigate with a large ship, but how do you even crash that high up?

### ISSUE THREAD

**Issue by joebobthethird** [Potion-Studios/Oh-The-Biomes-Weve-Gone#94]
![2024-08-23_14 24 34](https://github.com/user-attachments/assets/f093f78f-100f-4744-8055-7f076cd9a0c5)

**Comment by JT122406** [comment]
The only option we have here I believe is to just disable the shipwreck from spawning in this biome.
@CorgiTaco Might know more

**Comment by CorgiTaco** [comment]
Yeah I'll add structure blacklisting tag to corgilib

**Comment by desagas** [comment]
I actually like this "feature." As time goes on, spikes like these had to come from somewhere ... being pushed out of the ground? But, for me, it adds some lore potential.

**Comment by JT122406** [comment]
> I actually like this "feature." As time goes on, spikes like these had to come from somewhere ... being pushed out of the ground? But, for me, it adds some lore potential.

I feel like that's fair

**Comment by JT122406** [comment]
I think we decided to keep this as it looks cool to us, If @CorgiTaco Decides to add a structure blacklist tag that others can add structures/biomes there selves
