### ISSUE TITLE
Sheep do not eat off of lush grass blocks

### ISSUE THREAD

**Issue by Ace-Morrison** [Potion-Studios/Oh-The-Biomes-Weve-Gone#98]
![Minecraft Screenshot 2024 08 25 - 15 43 17 28](https://github.com/user-attachments/assets/3a97369f-7136-44dc-955f-a533b08445e4)

**Comment by JT122406** [comment]
I'm going to have to Mixin to EatBlockGoal#canUse or figure out something else
