### ISSUE TITLE
Grass blocks and Lush grass blocks don't spread to each other

### ISSUE THREAD

**Issue by Ace-Morrison** [Potion-Studios/Oh-The-Biomes-Weve-Gone#99]
![Minecraft Screenshot 2024 08 25 - 15 51 00 71](https://github.com/user-attachments/assets/58a25e1f-e443-4026-aefb-2b89c251a119)

**Comment by JT122406** [comment]
What exactly is this image showing?

**Comment by Ace-Morrison** [comment]
Including the image probably wasn't necessary but it shows that **Lush Grass Blocks** don't spread grass to **Dirt Blocks** and normal **Grass Blocks** don't spread grass to **Lush Dirt**. In my mind they should be compatible with each other.

**Comment by JT122406** [comment]
I believe this is our intended behavior but @AOCAWOL Would know more

**Comment by JT122406** [comment]
Can confirm this is intended behavior
